```{r}
library(tidyverse)
library(here)
library(ggsci)
library(janitor)
```



## BioProject
```{r}
animals_vaccines_bioproject_result <- read_csv("animals_vaccines_bioproject_result.csv", 
    col_names = FALSE)
datacuration_clean = animals_vaccines_bioproject_result %>%
 drop_na() %>% 
  mutate(study = if_else(X1 =="Title", X2, NA)) %>% 
  fill(study, .direction = c("down")) %>% 
  pivot_wider(names_from = X1, values_from = X2) %>% 
  select(-study) %>% 
  clean_names() %>% 
  mutate(title = str_remove(title, "^\\d+\\.\\s"),
         organism = str_remove(organism, "Organism: "),
         organism = str_remove(organism, "Taxonomy ID "),
         bio_project_accession = str_remove(bio_project_accession, "BioProject Accession: "),
         id = str_remove(id, "ID: "))

datacuration_clean

datacuration_clean %>% 
  write_csv(here("tables", "datacuration_step2.csv"))
```


```{r fig.height=5, fig.width=7}
datacuration_clean %>%
  group_by(organism) %>% 
  summarize(n_organism = n()) %>% 
  # filter(!str_detect(organism,"Homo sapiens")) %>% 
  arrange(-n_organism) %>% 
  ggplot() +
  aes(x = n_organism,
      y = organism %>% fct_reorder(n_organism)) +
  geom_col(fill = "black") + 
  theme_light()+
  geom_text(aes(label = n_organism),
            hjust = -0.2,
            size =3) +
  scale_x_continuous(expand = c(0.01,0.01),
                     limits = c(0, 900)) +
  theme(
    legend.position = c(0.95,0.5),
    plot.caption = element_text(hjust = 0, size = 5),
    axis.text.x = element_text(size = 10,
                               color = "black",
                               angle = 0),
    axis.text.y = element_text(size = 10,
                               color = "black",
                               angle = 0),
    legend.text = element_text(size = 10),
    legend.title = element_text(size = 12),
    plot.title = element_text(size = 15),
    axis.title.y = element_text(color = "black"),
    panel.border = element_blank(),
    panel.grid.major.y = element_line(size = 0, 
                                    linetype = 2,
                                    color = "gray75"),
    panel.grid.major.x = element_line(size = 0.25, 
                                    linetype = 2,
                                    color = "gray75"),
    axis.line.x = element_line(size = 0.5,
                               colour = "black",
                               linetype = 1),
    axis.line.y = element_line(size = 0 ,
                               colour = "black",
                               linetype = 1),
    axis.ticks.x = element_line(size = 0.5, color = "black"),
    axis.ticks.y = element_line(size = 0.5, color = "black"),
    panel.grid.minor = element_blank(),
    plot.margin = margin(1, 1, 0, 0, "cm")
  ) +
    labs(x = "Frequency",
       y = "",
       title = "BioProject data curation",
       subtitle = "Immunization and vaccination datasets",
       caption = "Search terms: (('vaccine'[All Fields] OR 'immunization'[All Fields]\nOR 'vaccinated'[All Fields] OR 'vaccination'[All Fields] OR 'vaccines'[All Fields]) AND 'transcriptome gene expression'[Filter]\n AND 'material transcriptome'[Filter] AND 'capture_whole'[Filter] AND 'org mammals'[Filter] AND 'Mus musculus'[Organism]") 
  
```
```{r}
mice_vaccination_mining = datacuration_clean %>% 
  filter(str_detect(organism,"Mus musculus")) %>% 
  filter(!str_detect(str_to_lower(title), "cancer|tumor|autoimmune|drug")) %>% 
  filter(str_detect(str_to_lower(title), "vaccin|immuniz"))


mice_vaccination_mining
```


BioProject metadata
```{r}
library(rentrez)

#Single
bioprojectid = mice_vaccination_mining$id[[1]]
bioproject_meta = entrez_summary(db = "bioproject", id = bioprojectid) %>% 
  as.tibble() %>% 
  select(project_name,
         project_description,
         organism_name,
         project_id,
         project_data_type,
         project_target_material,
         project_target_capture,
         organism_name)


#Loop
bioproject_ids <- mice_vaccination_mining$id
bioproject_metadata_df <- map_dfr(bioproject_ids, ~
  entrez_summary(db = "bioproject", id = .x) %>%
    as.list() %>%
    as_tibble() %>%
    select(
      project_name,
      project_description,
      organism_name,
      project_data_type,
      project_target_material,
      project_target_capture
    ) %>%
    mutate(bioproject_id = .x)
)


bioproject_metadata_df = bioproject_metadata_df %>% 
  filter(!str_detect(project_description, "cancer|neoantigen|tumor|autoimmune|drug|opioid"))

# Visualizar
bioproject_metadata_df %>% 
  write_excel_csv2(here("tables", "mice_vaccination_mining2.csv"))

mice_vaccination_mining2 <- read_delim("tables/mice_vaccination_mining2.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)


bioproject_metadata_df

```


GEO
```{r}
library(glue)
#Single ------
# query NCBI GEO 
geo_ids <- "GSE199750"
terms <- entrez_db_searchable(db = "gds")  # for reference: searchable fields
# first, get additional information about this series, including its db ID.
series <- entrez_search("gds",
                        term = glue("{geo_ids}[ACCN] AND gse[ETYP]"))
# use the ID to fetch details, including the sample table
series_summary = entrez_summary(db = "gds", id = series$ids)
series_summary_df = data_frame(bioproject = series_summary$bioproject,
                               uid = series_summary$uid,
                               gse= series_summary$gse,
                               gds= series_summary$gds,
                               title= series_summary$title,
                               summary= series_summary$summary,
                               gpl= series_summary$gpl,
                               n_samples= series_summary$n_samples,
                               platformtitle= series_summary$platformtitle)

#Multiple -------

# geo_ids = read_delim(here("tables", "gds_result.txt"), delim = "\n", col_names = F) %>% 
#   mutate(X1 = str_c("GSE", X1, sep = "") %>% 
#            str_remove(., "200"))
#   pull()

text = readLines(here("tables", "gds_result (1).txt"))
text_collapsed <- paste(text, collapse = "\n")
gse_ids <- str_extract_all(conteudo, "GSE\\d+\\b") %>% unlist() %>% unique()


geo_metadata_df <- map_dfr(gse_ids, ~ {
  result <- entrez_search("gds", term = glue("{.x}[ACCN] AND gse[ETYP]"))

  if (length(result$ids) == 0) {
    return(tibble(gse = .x, error = "Not found"))
  }

  summary <- entrez_summary(db = "gds", id = result$ids)

  tibble(
    gse = .x,
    uid = summary$uid,
    gds = summary$gds,
    bioproject = summary$bioproject,
    title = summary$title,
    summary_text = summary$summary,
    gpl = summary$gpl,
    n_samples = summary$n_samples,
    platformtitle = summary$platformtitle
  ) %>% 
    mutate(bioproject_id = str_remove(bioproject, "PRJNA"))
})
print(geo_metadata_df)

  
  
```


Merge by Bioproject ID
```{r}
mice_vaccination_mining_ManualAnnotation <- read_csv(here("tables", "mice_vaccination_mining_ManualAnnotation.csv")) %>% 
  mutate(bioproject_id = as.character(bioproject_id),
         project_id = as.character(project_id)) %>% 
  drop_na(project_id)


mice_vaccination_annotated = geo_metadata_df %>% 
  right_join(mice_vaccination_mining_ManualAnnotation,
             by = "bioproject_id") %>% 
  select(title, summary_text,
         project_description, n_samples,
         notes, keywords, timepoints:project_target_material,
         gse, bioproject_id
         ) %>% 
  arrange(-n_samples)

mice_vaccination_annotated %>% 
  write_csv(here("tables", "mice_vaccination_annotated.csv"))

mice_vaccination_annotated
```





