---
title: "4_Performance_Biocontrol"
output: html_document
---
#Required

```{r message=FALSE, warning=FALSE}
# install.packages("here") if needed
library(here)
source(here("scripts_notebooks", "required.R"))
# Add DMD to organism color palette
colors$organism["DMD"] = "#2ec4b6"
```

# Performance tests 

# 1. All conditions

## Classification: Genes




```{r}
#Import ============
btm_annotation_genes = read_csv(file = here("tables", "btm_annotation_genes.csv"))
#Metadata 
all_human_mouse_metadata = readRDS(here("tables", "all_human_mouse_metadata.rds")) 

#DEGs table 
all_degs_human_mouse_unmatched =
  readRDS(file = here("tables", "all_human_mouse_dge_limma_degs.rds")) %>% 
  mutate(pathogen = case_when(pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              pathogen == "Hepatitis B" ~ "HepB",
                              T ~ pathogen)) %>%
  mutate(timepoint = if_else(pathogen %in% c("Burn", "Trauma") & timepoint %in% c("2h", "Early hours"), 
                             "Early hours", 
                             timepoint))

#Biological negative control
biological_null_degs = readRDS(file = here("tables", "duchenne_mouse_dge_limma_degs.rds")) %>% 
  filter(timepoint == "Day 28")

#Check
all_degs_human_mouse_unmatched %>% dplyr::count(pathogen, organism, timepoint)
```


```{r}
#1. Create pairs (different days, by pathogen and organism)
#Human timepoint vs Mouse different timepoints
all_degs_human_mouse_matched = 
  bind_rows(
  #Match different Human timepoints with different Mouse timepoints
  all_degs_human_mouse_unmatched %>% 
  filter(organism == "Human") %>% 
  inner_join(all_degs_human_mouse_unmatched %>% 
               filter(organism == "Mouse") %>% 
               select(pathogen, timepoint) %>% 
               distinct(),
             by = "pathogen", suffix = c("_human", "_mouse")) %>% 
    mutate(timepoint_comparison = paste0(timepoint_human, "-", timepoint_mouse)) %>% 
    mutate(timepoint = timepoint_human),
  #Match different Mouse timepoints with different Human timepoints
  all_degs_human_mouse_unmatched %>% 
  filter(organism == "Mouse") %>% 
  inner_join(all_degs_human_mouse_unmatched %>% 
               filter(organism == "Human") %>% 
               select(pathogen, timepoint) %>% 
               distinct(),
             by = "pathogen", suffix = c("_mouse", "_human")) %>% 
    mutate(timepoint_comparison = paste0(timepoint_human, "-", timepoint_mouse)) %>% 
    mutate(timepoint = timepoint_human)) 
  
all_degs_human_mouse_matched %>% 
  dplyr::count(pathogen, organism, treatment, timepoint_comparison)

#2. Filter comparisons based on correlation
conditions_filtered =
  readRDS(file = here("tables", "all_human_mouse_correlation_filtered_inter_weighted_filtered.rds")) %>% 
  select(treatment_human, treatment_mouse, pathogen_human, pathogen_mouse,
         pathogen_comparison, timepoint_comparison,
         timepoint_human, timepoint_mouse) %>% 
  distinct() %>% 
  pivot_longer(
    cols = contains("_human") | contains("_mouse"), 
    names_to = c(".value", "organism"),             
    names_sep = "_",                                
    values_drop_na = TRUE
  ) %>% 
  mutate(organism = str_to_title(organism)) %>% 
  mutate(timepoint = str_replace_all(timepoint, "\n", " "))

#3. Filter timepoints 
all_degs_human_mouse_matched_filtered = all_degs_human_mouse_matched %>% 
  select(organism:human_symbol, mean_l2fc:sd, timepoint_comparison) %>% 
  inner_join(conditions_filtered,
             by = join_by(organism, pathogen,treatment,  timepoint_comparison))
#Check
all_degs_human_mouse_matched_filtered %>% 
  dplyr::count(treatment, pathogen, organism, timepoint_comparison)



######################
#Bind negative control
######################
all_degs_human_mouse_matched_filtered_bionull = 
  bind_rows(
  #Keep original 
  all_degs_human_mouse_matched_filtered,
          
  #Match control with different pathogens and bind
  biological_null_degs %>% 
  mutate(organism = "DMD") %>% 
  select(human_symbol:ave_expr, t:b, se, sd, organism) %>% 
  crossing(all_degs_human_mouse_matched_filtered %>% 
               select(pathogen, timepoint_comparison, treatment) %>% 
               distinct())
  )
  

all_degs_human_mouse_matched_filtered_bionull %>% 
  dplyr::count(treatment, pathogen, organism, timepoint_comparison)
```

```{r}

#Input ======================
genes_roc_allgenes = all_degs_human_mouse_matched_filtered_bionull %>%
  select(pathogen, treatment, organism, human_symbol, timepoint_comparison, mean_l2fc, adj_p_val, everything())

genes_roc_allgenes %>% dplyr::count(pathogen, organism,  timepoint_comparison)

#All genes
genes_roc_allgenes

#Filter immune genes
genes_roc_allgenes_immunegenes = genes_roc_allgenes %>%
  filter(human_symbol %in% c(btm_annotation_genes %>%
                         filter(module_category == "immune") %>%
                         pull(symbol) %>%
                         unique()))

#Only DEGs
degs_genes_human = genes_roc_allgenes %>%
  filter(adj_p_val <= 0.05,
         organism == "Human") %>%
  select(human_symbol, pathogen, organism, timepoint_comparison)

#Only DEGs
genes_roc_DEGs_all = genes_roc_allgenes %>%
  inner_join(degs_genes_human %>%
               select(-organism),
             by = join_by("human_symbol", "pathogen", "timepoint_comparison"))

#Only immune DEGs
genes_roc_DEGs_immune = genes_roc_allgenes %>%
  inner_join(degs_genes_human %>%
               select(-organism),
             by = join_by("human_symbol", "pathogen", "timepoint_comparison")) %>%
  #Filter immune genes only
  filter(human_symbol %in% c(btm_annotation_genes$symbol %>% unique()))

genes_roc_allgenes %>%
  dplyr::count(pathogen, organism, timepoint_comparison)

degs_genes_human %>%
  dplyr::count(pathogen, organism, timepoint_comparison)

genes_roc_DEGs_all %>%
  dplyr::count(pathogen, organism, timepoint_comparison)

genes_roc_DEGs_immune %>%
  dplyr::count(pathogen, timepoint_comparison)

```


Inputs
Double check the code
```{r fig.height=4, fig.width=10}
set.seed(123)
# ######## Input -----
filename = "all_human_mouse"
gene_set_filename = "All_OnlyImmune"
genes_df_input = bind_rows(
  genes_roc_allgenes %>% mutate(model_type = "Mouse"),
  genes_roc_allgenes_immunegenes %>% mutate(model_type = "Immune")
)

# filename = "all_human_mouse"
# gene_set_filename = "HumanDEGs_OnlyImmune"
# genes_df_input = bind_rows(
#   genes_roc_DEGs_all %>% mutate(model_type = "Mouse"),
#   genes_roc_DEGs_immune %>% mutate(model_type = "Immune")
# )

```

Compute probabilities
```{r fig.height=6, fig.width=10}
#=====================================================
# Compute probabilities
#=====================================================
# Up
dge_long_genes_up <- genes_df_input %>% 
  mutate(
    # Classify genes based on statistical significance (FDR) and direction of change
    direction = case_when(
      adj_p_val <= 0.05 & mean_l2fc > 0 ~ "up",
      TRUE                              ~ "not_up"
    ),
    # Assign a probability score based on confidence (1 - FDR)
    prob = 1 - adj_p_val 
  ) 
#Check
dge_long_genes_up %>% 
  dplyr::count(pathogen, timepoint_comparison, organism, direction)

#Down
dge_long_genes_down = genes_df_input %>% 
  mutate(
    # Classify genes based on statistical significance (FDR) and direction of change
    direction = case_when(
      adj_p_val <= 0.05 & mean_l2fc < 0 ~ "down",
      TRUE                              ~ "not_down"
    ),
    # Assign a probability score based on confidence (1 - FDR)
    prob = 1 - adj_p_val 
  )

#Check
dge_long_genes_down %>% 
  dplyr::count(pathogen, timepoint_comparison, organism, direction)



```


```{r fig.height=6, fig.width=10}
#=====================================================
# Assign human truth
#=====================================================
truth_human_up = dge_long_genes_up %>% 
  select(human_symbol, pathogen, organism, timepoint_comparison, adj_p_val, direction) %>% 
  filter(organism == "Human") %>% 
  distinct() %>% 
  pivot_wider(names_from = organism, values_from = direction) %>% 
  rename(truth = Human) %>% 
  mutate(organism = "Human")


truth_human_down = dge_long_genes_down %>% 
  select(human_symbol, pathogen, organism, timepoint_comparison, adj_p_val, direction) %>% 
  filter(organism == "Human") %>% 
  distinct() %>% 
  pivot_wider(names_from = organism, values_from = direction) %>% 
  rename(truth = Human) %>% 
  mutate(organism = "Human")

#=====================================================
#Generate reference distributions
#=====================================================
perfect_prediction_up = truth_human_up %>%
  mutate(prob = if_else(truth == "up", 1, 0),
         model = "Human") %>%
  rename(pred = truth)

perfect_prediction_down = truth_human_down %>%
  mutate(prob = if_else(truth == "down", 1, 0),
          model = "Human") %>%
  rename(pred = truth)

# permutation_prediction_up = perfect_prediction_up %>%
#   group_by(pathogen, timepoint_comparison) %>% 
#   mutate(prob = runif(n()), organism = "Permutation",
#          model = "Permutation")

# permutation_prediction_down = perfect_prediction_down %>%
#   group_by(pathogen, timepoint_comparison) %>% 
#   mutate(prob = runif(n()), 
#          organism = "Permutation",
#          model = "Permutation")

#=====================================================
# Combine models (Mouse + Immune + Permutation + Perfect)
#=====================================================
models_up = dge_long_genes_up %>% 
  filter(organism != "Human") %>% 
  mutate(pred = direction,
         organism,
         model = if_else(model_type == "Immune", "Immune", organism)) %>%
  bind_rows(perfect_prediction_up)

models_down = dge_long_genes_down %>% 
  filter(organism != "Human") %>% 
  mutate(pred = direction,
         model = if_else(model_type == "Immune", "Immune", organism)) %>%
  bind_rows(perfect_prediction_down)

#=====================================================
# Classify probabilities 
#=====================================================
classified_df_probs_up = truth_human_up %>% 
  select(human_symbol, pathogen, timepoint_comparison, truth) %>%
  inner_join(models_up %>% 
               select(human_symbol, organism, pathogen, timepoint_comparison, pred, prob, model),
             by = join_by(human_symbol, timepoint_comparison, pathogen)) %>% 
  mutate(
    truth = factor(truth, levels = c("up", "not_up"))
  ) %>% 
  distinct()

classified_df_probs_down = truth_human_down %>% 
  select(human_symbol, pathogen, timepoint_comparison, truth) %>%
  inner_join(models_down %>% 
               select(human_symbol, organism, pathogen, timepoint_comparison, pred, prob, model),
             by = join_by(human_symbol, timepoint_comparison, pathogen)) %>% 
  mutate(
    truth = factor(truth, levels = c("down", "not_down"))
  ) %>% 
  distinct() 


classified_df_probs_up_DEGs = truth_human_up %>% 
  select(human_symbol, pathogen, timepoint_comparison, truth) %>%
  inner_join(models_up %>% 
               select(human_symbol, organism, pathogen, timepoint_comparison, pred, prob, model),
             by = join_by(human_symbol, timepoint_comparison, pathogen)) %>% 
  mutate(
    truth = factor(truth, levels = c("up", "not_up"))
  ) %>% 
  distinct() %>% 
    inner_join(degs_genes_human %>% 
               select(-organism), 
             by = join_by(human_symbol, pathogen, timepoint_comparison))



classified_df_probs_down_DEGs = truth_human_down %>% 
  select(human_symbol, pathogen, timepoint_comparison, truth) %>%
  inner_join(models_down %>% 
               select(human_symbol, organism, pathogen, timepoint_comparison, pred, prob, model),
             by = join_by(human_symbol, timepoint_comparison, pathogen)) %>% 
  mutate(
    truth = factor(truth, levels = c("down", "not_down"))
  ) %>% 
  distinct()  %>% 
    inner_join(degs_genes_human %>% 
               select(-organism), 
             by = join_by(human_symbol, pathogen, timepoint_comparison))

#Check
classified_df_probs_up  %>% 
  dplyr::count(pathogen, model, timepoint_comparison, pred, truth)

classified_df_probs_up_DEGs %>% 
  dplyr::count(pathogen, model, timepoint_comparison, pred, truth)

classified_df_probs_down %>% 
  dplyr::count(pathogen, model, timepoint_comparison, pred, truth)

classified_df_probs_down_DEGs %>% 
  dplyr::count(pathogen, model, timepoint_comparison, pred, truth)
```



```{r fig.height=6, fig.width=10}
#=====================================================
#Compute ROC 
#=====================================================

#UP-notUP
roc_curve_up_notup = classified_df_probs_up %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_curve(truth, prob) %>%
  mutate(comparison = "Up")

roc_curve_up_notup_DEGs = classified_df_probs_up_DEGs %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_curve(truth, prob) %>%
  mutate(comparison = "Up")

roc_curve_up_notup %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

roc_curve_up_notup_DEGs %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

#DOWN-notDOWN
roc_curve_down_notdown = classified_df_probs_down %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation",  "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_curve(truth, prob) %>%
  mutate(comparison = "Down")

roc_curve_down_notdown_DEGs = classified_df_probs_down_DEGs %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_curve(truth, prob) %>%
  mutate(comparison = "Down")

roc_curve_down_notdown %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

roc_curve_down_notdown_DEGs %>% 
  dplyr::count(pathogen, model, timepoint_comparison)



```


```{r fig.height=6, fig.width=10}
#=====================================================
#Compute AUC 
#=====================================================
auc_results_up = classified_df_probs_up %>% 
  mutate(truth = fct_relevel(truth, "up", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "DMD", "Permutation", "Human")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_auc(truth, prob) %>%
  rename(auc = .estimate) %>%
  mutate(comparison = "Up") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, auc, comparison)

auc_results_up_DEGs = classified_df_probs_up_DEGs %>% 
  mutate(truth = fct_relevel(truth, "up", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "DMD", "Permutation", "Human")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_auc(truth, prob) %>%
  rename(auc = .estimate) %>%
  mutate(comparison = "Up") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, auc, comparison)

auc_results_down = classified_df_probs_down %>% 
  mutate(truth = fct_relevel(truth, "down", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "DMD", "Permutation", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_auc(truth, prob) %>%
  rename(auc = .estimate) %>%
  mutate(comparison = "Down") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, auc, comparison)

auc_results_down_DEGs = classified_df_probs_down_DEGs %>% 
  mutate(truth = fct_relevel(truth, "down", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "DMD", "Permutation", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  roc_auc(truth, prob) %>%
  rename(auc = .estimate) %>%
  mutate(comparison = "Down") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, auc, comparison)


##### Unite all results
roc_curve_auc_df = bind_rows(auc_results_up,
                             auc_results_down) %>% 
  inner_join(
    roc_curve_up_notup %>% 
      bind_rows(roc_curve_down_notdown %>% 
                  filter(model != "Human")),
    by = join_by(pathogen, model, timepoint_comparison, comparison)) %>% 
    mutate(model = fct_relevel(model, "Human", "Mouse", "DMD", "Immune", "Permutation"),
         comparison = fct_relevel(comparison, "Up", "Down"),
         # timepoint_comparison = str_replace(timepoint_comparison, "Early hours", "Early\nhours"),
         # timepoint_comparison = fct_relevel(timepoint_comparison, c("Early hours", "2h", "4h", "6h", "12h", "24h", "Day 1", "Day 3", "Day 7")),
         pathogen = case_when(pathogen == "Hepatitis B" ~ "HepB",
                              pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              T ~ pathogen),
         pathogen = fct_relevel(pathogen, "Influenza", "HepB", "S. aureus", "E. coli", "Burn", "Trauma")) %>% 
  mutate(auc = round(auc, 2) %>% as.character())


roc_curve_auc_df_DEGs = bind_rows(auc_results_up_DEGs,
                                  auc_results_down_DEGs) %>% 
  inner_join(
    roc_curve_up_notup_DEGs %>% 
      bind_rows(roc_curve_down_notdown_DEGs %>% 
                  filter(model != "Human")),
    by = join_by(pathogen, model, timepoint_comparison, comparison)) %>% 
    mutate(model = fct_relevel(model, "Human", "Mouse", "DMD", "Immune", "Permutation"),
         comparison = fct_relevel(comparison, "Up", "Down"),
         # timepoint_comparison = str_replace(timepoint_comparison, "Early hours", "Early\nhours"),
         # timepoint_comparison = fct_relevel(timepoint_comparison, c("Early hours", "2h", "4h", "6h", "12h", "24h", "Day 1", "Day 3", "Day 7")),
         pathogen = case_when(pathogen == "Hepatitis B" ~ "HepB",
                              pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              T ~ pathogen),
         pathogen = fct_relevel(pathogen, "Influenza", "HepB", "S. aureus", "E. coli", "Burn", "Trauma")) %>% 
  mutate(auc = round(auc, 2) %>% as.character())

roc_curve_auc_df %>% 
  dplyr::count(pathogen, model, comparison, timepoint_comparison, auc)

roc_curve_auc_df_DEGs %>% 
  dplyr::count(pathogen, model, comparison, timepoint_comparison, auc)
```



### Plot ROC curve
```{r fig.height=10, fig.width=6}
#Plot curves ------------------
#PLOT ROC Curve
roc_curve_plot = roc_curve_auc_df %>% 
  arrange(pathogen) %>% 
  ungroup() %>% 
  ggplot(aes(x = 1 - specificity, 
             y = sensitivity, 
             color = model,
             linetype = comparison)) +
  geom_path(size = 0.75, alpha = 1) +
  geom_abline(lty = 3) +
  theme_vaxgo() +
  facet_nested_wrap(~pathogen+timepoint_comparison, nrow = 3, axes = "x",
                    strip = strip_nested(size = "variable")) +
  #Mouse
  geom_text(data = . %>% 
              filter(model == "Mouse", comparison == "Up") %>% 
              select(pathogen, model, comparison, timepoint_comparison, auc) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, auc),
                color = model,
                x = 1,
                y = 0.4),
            size = 2,
            hjust = 1) +
  geom_text(data = . %>% 
              filter(model == "Mouse", comparison == "Down") %>% 
              select(pathogen, model, comparison, timepoint_comparison, auc) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, auc),
                color = model,
                x = 1,
                y = 0.3),
            size = 2,
            hjust = 1) +
  #Immune
  geom_text(data = . %>% 
              filter(model == "Immune", comparison == "Up") %>% 
              select(pathogen, model, comparison, timepoint_comparison, auc) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, auc),
                color = model,
                x = 1,
                y = 0.2),
            size = 2,
            hjust = 1) +
   geom_text(data = . %>% 
              filter(model == "Immune", comparison == "Down") %>% 
              select(pathogen, model, comparison, timepoint_comparison, auc) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, auc),
                color = model,
                x = 1,
                y = 0.1),
            size = 2,
            hjust = 1) +
  scale_linetype_manual(values = c("Up" = 1,
                                   "Down" = 2)) +
  # coord_equal() +
  scale_color_manual(values = colors$organism) +
  labs(
  x = "FPR",
  y = "TPR",
  color = "Model",
  linetype = "Comparison") + 
  guides(fill = guide_legend(override.aes = list(size = 4)),
         color = guide_legend(override.aes = list(linewidth = 4, shape = 1))
         ) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
          axis.title.x = element_text(size = 8),
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5),
          strip.text.x = element_text(angle = 0, hjust = 0., vjust = 0.5, size = 8),
          legend.position = "top",
          legend.direction = "horizontal", 
          legend.text = element_text(size = 8, hjust = 0),
          legend.title = element_text(size = 8),
          legend.spacing.x = unit(0, 'cm'),
          legend.spacing.y = unit(0, 'cm'),
          ggh4x.facet.nestline = element_line(colour = "black", linetype = 1),
          legend.box.spacing = unit(0, "cm"),
          panel.spacing.y = unit(0, "lines"), 
          panel.spacing.x = unit(1, "lines"), 
          plot.margin = margin(0, 0.3, 0, 0, unit = "cm"),
          
          ) +
  scale_x_continuous(n.breaks = 3) +
  scale_y_continuous(n.break = 3) +
  guides(linetype = guide_legend(override.aes = list(linewidth = 0.5, size = 1),
                                 order = 2), 
         fill = "none",
         color = guide_legend(override.aes = list(linewidth = 3)))

roc_curve_plot

roc_curve_auc_df %>% 
  dplyr::count(pathogen, timepoint_comparison, comparison, model)

# roc_curve_plot %>%
#   ggsave(filename = here("Figures", paste0(filename, "_performance_roc_", gene_set_filename, ".png")),
#          width = 8,
#          height = 5)
```

AUC as heatmap

```{r}
#Get n genes
ngenes = bind_rows(
  classified_df_probs_up %>%
    filter(pred == "up") %>% 
  group_by(pathogen, timepoint_comparison, model) %>% 
  summarise(n_genes = n(),
            comparison = "Up") %>% 
    ungroup(),
  classified_df_probs_down %>%
    filter(pred == "down") %>% 
  group_by(pathogen, timepoint_comparison, model) %>% 
  summarise(n_genes = n(),
            comparison = "Down") %>% 
    ungroup(),
)


# Visualize AUC
roc_auc_df <- roc_curve_auc_df %>%
  inner_join(ngenes, by = join_by(comparison, pathogen, timepoint_comparison, model)) %>% 
  mutate(model = fct_relevel(model, "Human", "Mouse", "Immune", "Permutation", "DMD", "FIT"),
         comparison = fct_relevel(comparison, "Up", "Down"),
         # timepoint = str_replace(timepoint, "Early hours", "Early\nhours"),
         # timepoint = fct_relevel(timepoint, c("Early\nhours", "2h", "4h", "6h", "12h", "24h", "Day 1", "Day 3", "Day 7")),
         pathogen = case_when(pathogen == "Hepatitis B" ~ "HepB",
                              pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              T ~ pathogen),
         pathogen = fct_relevel(pathogen, "Influenza", "HepB", "S. aureus", "E. coli", "Burn", "Trauma"),
         treatment = case_when(pathogen %in% c("HepB", "Influenza") ~ "Vaccination",
                               pathogen %in% c( "S. aureus", "E. coli") ~ "Infection",
                               pathogen %in% c( "Burn", "Trauma") ~ "Injury",
                               T ~ pathogen),
         treatment = fct_relevel(treatment, "Vaccination", "Infection", "Injury")
         ) 

roc_auc_heatmap = roc_auc_df %>% 
  ggplot() +
   aes(x = comparison,
      y = model %>% fct_rev(),
      fill = auc,
      color = model %>% fct_rev(),
      group = model %>% fct_rev()) + 
  
  facet_nested_wrap(~treatment+pathogen+timepoint_comparison,
                    # scales = "free",
                    nrow = 1,
                    strip = strip_nested(size = "variable")
                    ) +
  
  geom_tile(color = "black",
             stroke = 0.5) + 
  
  #Add labels
  geom_text(aes(label = round(auc, 2)), size = 3,
             color = "black",
             fontface = "bold",
             vjust = 0.25,
            data = . %>% filter(auc <= 0.7)) +
  geom_text(aes(label = round(auc, 2)), size = 3,
             color = "white",
             fontface = "bold",
             vjust = 0.25,
            data = . %>% filter(auc > 0.7)) +
   geom_text(aes(label = paste0("n=", n_genes)), size = 2,
             color = "black",
             vjust = 2,
             data = . %>% filter(auc <= 0.7)) +
  
   geom_text(aes(label = paste0("n=", n_genes)), size = 2,
             color = "white",
             vjust = 2,
             data = . %>% filter(auc > 0.7)) +
 

  scale_x_discrete(expand = c(0.05, 0.05)) +
  # scale_y_continuous(expand = c(0.01, 0.01)) +
  theme_vaxgo() +
    scale_fill_gradientn(
        colors = c("white", "#4DBBD5FF","#4361ee"),
        values = scales::rescale(seq(0, 1, length.out = 10)),
        limits = c(0, 1),
        name = "PR_AUC",
        guide = guide_colorbar(
          barwidth = 15,
          barheight = 1,
          nbin = 10,
          raster = FALSE
        )
      ) +
  labs(
    x = "Comparison",
    y = "Model",
    fill = "ROC-AUC",
  ) +
    theme(axis.text.x = element_text(angle = 0,  hjust = 0.5, vjust = 1, size = 8),
          axis.text.y = element_text(size = 8, hjust = 1),
          axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          strip.text = element_text(size = 8, margin = margin(1, 0, 1, 0)),
          strip.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, size = 8),
          strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5, size = 8),
          panel.spacing = unit(1, "lines"),
          plot.margin = margin(0, 0.5, 0, 0, unit = "cm"),
          legend.position = "top",
          legend.direction = "horizontal",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-10,0),
          legend.text = element_text(size = 8, hjust = 0),
          legend.title = element_text(size = 8),
          ggh4x.facet.nestline = element_line(colour = "black", linetype = 1, size = 0.5)
    ) 

pr_auc_heatmap
  

# pr_auc_heatmap %>%
#   ggsave(filename = here("Figures", "all_human_mouse_performance_roc_auc_heatmap_All_OnlyImmune.png"),
#          width = 8,
#          height = 3)
```


AUC as lineplots
```{r fig.height=12, fig.width=3}

auc_lineplot = auc_lineplot_df %>% 
  ggplot() +
   aes(x = timepoint_comparison,
      y = auc,
      fill = model,
      color = model,
      group = model) + 
  
  facet_nested_wrap(~treatment+pathogen+comparison,
                    scales = "free",
                    ncol = 2,
                    strip = strip_nested(size = "variable")
                    ) +
  
  geom_line(width = 1,
            aes(linetype = model)) +
  
  geom_point(size = 2,
             pch = 21,
             color = "black",
             stroke = 0.5) + 
  geom_text_repel(aes(label = n_genes), size = 2) +
  # Add a reference line for random prediction (AUC = 0.5)
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "black", linewidth = 0.2) +
  # geom_text_repel(aes(label = auc), 
  #                 size = 2.5, 
  #                 # direction = "y", 
  #                 segment.alpha = 1) +

  scale_x_discrete(expand = c(0.05, 0.05)) +
  # scale_y_continuous(expand = c(0.01, 0.01)) +
  theme_vaxgo() +
  scale_linetype_manual(values = c(
    "Mouse" = 1,
    "Immune" = 1,
    "Human" = 1,
    "Permutation" = 2
    )) +
  scale_fill_manual(values = colors$organism) +
  scale_color_manual(values = colors$organism) +
  labs(
    x = "Time",
    y = "AUC",
    fill = "Model",
    shape = "Model",
  ) +
    theme(axis.text.x = element_text(angle = 0,  hjust = 0.5, vjust = 1, size = 8),
          axis.text.y = element_text(size = 8, hjust = 1),
          axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          strip.text = element_text(size = 8, margin = margin(1, 0, 1, 0)),
          strip.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, size = 8),
          strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5, size = 8),
          panel.spacing = unit(0, "lines"),
          plot.margin = margin(0, 0.5, 0, 0, unit = "cm"),
          legend.position = "top",
          legend.direction = "horizontal",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-10,0),
          legend.text = element_text(size = 8, hjust = 0),
          legend.title = element_text(size = 8),
          ggh4x.facet.nestline = element_line(colour = "black", linetype = 1, size = 0.5)
    ) +
  guides(color = "none",
         shape = "none",
         linetype = "none",
         fill = guide_legend(nrow = 2, by.row = T))

auc_lineplot
# auc_lineplot %>%
#   ggsave(filename = here("Figures", "all_human_mouse_performance_roc_auc_lineplot_All_OnlyImmune.png"),
#          width = 3,
#          height = 12)

```



###Plot PR curve

Compute PR 

```{r fig.height=6, fig.width=10}
#=====================================================
#Compute PR 
#=====================================================

pr_curve_up_notup = classified_df_probs_up %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_curve(truth, prob) %>%
  mutate(comparison = "Up")

pr_curve_up_notup_DEGs = classified_df_probs_up_DEGs %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_curve(truth, prob) %>%
  mutate(comparison = "Up")

pr_curve_up_notup %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

pr_curve_up_notup_DEGs %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

pr_curve_down_notdown = classified_df_probs_down %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_curve(truth, prob) %>%
  mutate(comparison = "Down")

pr_curve_down_notdown_DEGs = classified_df_probs_down_DEGs %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "DMD", "Human", "FIT")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_curve(truth, prob) %>%
  mutate(comparison = "Down")

pr_curve_down_notdown %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

pr_curve_down_notdown_DEGs %>% 
  dplyr::count(pathogen, model, timepoint_comparison)

#=====================================================
#Compute PR-AUC 
#=====================================================
pr_auc_results_up = classified_df_probs_up %>% 
  mutate(truth = fct_relevel(truth, "up", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "Human", "FIT", "DMD")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_auc(truth, prob) %>%
  rename(pr_auc = .estimate) %>%
  mutate(comparison = "Up") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, pr_auc, comparison)

pr_pr_auc_results_up_DEGs = classified_df_probs_up_DEGs %>% 
  mutate(truth = fct_relevel(truth, "up", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "Human", "FIT", "DMD")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_auc(truth, prob) %>%
  rename(pr_auc = .estimate) %>%
  mutate(comparison = "Up") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, pr_auc,  comparison)

pr_auc_results_down = classified_df_probs_down %>% 
  mutate(truth = fct_relevel(truth, "down", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "Human", "FIT", "DMD")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_auc(truth, prob) %>%
  rename(pr_auc = .estimate) %>%
  mutate(comparison = "Down") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, pr_auc,  comparison)

pr_pr_auc_results_down_DEGs = classified_df_probs_down_DEGs %>% 
  mutate(truth = fct_relevel(truth, "down", after = 0)) %>% 
  filter(model %in% c("Mouse", "Immune", "Permutation", "Human", "FIT", "DMD")) %>%
  group_by(pathogen, model, timepoint_comparison) %>%
  pr_auc(truth, prob) %>%
  rename(pr_auc = .estimate) %>%
  mutate(comparison = "Down") %>% 
  ungroup() %>% 
  select(pathogen, model, timepoint_comparison, pr_auc,  comparison)


##### Unite all results
pr_curve_auc_df = bind_rows(pr_auc_results_up,
                             pr_auc_results_down) %>% 
  inner_join(
    pr_curve_up_notup %>% 
      bind_rows(pr_curve_down_notdown %>% 
                  filter(model != "Human")),
    by = join_by(pathogen, model, timepoint_comparison, comparison)) %>% 
    mutate(model = fct_relevel(model, "Mouse", "Immune", "Permutation", "Human", "FIT", "DMD"),
         comparison = fct_relevel(comparison, "Up", "Down"),
         # timepoint_comparison = str_replace(timepoint_comparison, "Early hours", "Early\nhours"),
         # timepoint_comparison = fct_relevel(timepoint_comparison, c("Early hours", "2h", "4h", "6h", "12h", "24h", "Day 1", "Day 3", "Day 7")),
         pathogen = case_when(pathogen == "Hepatitis B" ~ "HepB",
                              pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              T ~ pathogen),
         pathogen = fct_relevel(pathogen, "Influenza", "HepB", "S. aureus", "E. coli", "Burn", "Trauma")) %>% 
  mutate(pr_auc = round(pr_auc, 2) %>% as.character())

pr_curve_auc_df_DEGs = bind_rows(pr_pr_auc_results_up_DEGs,
                                 pr_pr_auc_results_down_DEGs) %>% 
  inner_join(
    pr_curve_up_notup_DEGs %>% 
      bind_rows(pr_curve_down_notdown_DEGs %>% 
                  filter(model != "Human")),
    by = join_by(pathogen, model, timepoint_comparison, comparison)) %>% 
    mutate(model = fct_relevel(model, "Mouse", "Immune", "Permutation", "Human", "FIT", "DMD"),
         comparison = fct_relevel(comparison, "Up", "Down"),
         # timepoint = str_replace(timepoint, "Early hours", "Early\nhours"),
         # timepoint_comparison = fct_relevel(timepoint_comparison, c("Early hours", "2h", "4h", "6h", "12h", "24h", "Day 1", "Day 3", "Day 7")),
         pathogen = case_when(pathogen == "Hepatitis B" ~ "HepB",
                              pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              T ~ pathogen),
         pathogen = fct_relevel(pathogen, "Influenza", "HepB", "S. aureus", "E. coli", "Burn", "Trauma")) %>% 
  mutate(pr_auc = round(pr_auc, 2) %>% as.character())


pr_curve_auc_df %>% 
  dplyr::count(pathogen, model, comparison, timepoint_comparison, pr_auc)

pr_curve_auc_df_DEGs %>% 
  dplyr::count(pathogen, model, comparison, timepoint_comparison, pr_auc)

```

Plot PR curve
```{r fig.height=6, fig.width=10}
#Plot curves ------------------
#PLOT PR Curve
pr_curve_plot = pr_curve_auc_df %>% 
  arrange(pathogen) %>% 
  ungroup() %>% 
  ggplot(aes(x = recall, 
             y = precision, 
             color = model,
             linetype = comparison)) +
  geom_path(size = 0.75, alpha = 1) +
  theme_vaxgo() +
  facet_nested_wrap(~pathogen+timepoint_comparison, nrow = 3, axes = "x",
                    strip = strip_nested(size = "variable")) +
  #Mouse
  geom_text(data = . %>% 
              filter(model == "Mouse", comparison == "Up") %>% 
              select(pathogen, model, comparison, timepoint_comparison, pr_auc) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, pr_auc),
                color = model,
                x = 1,
                y = 0.4),
            size = 2,
            hjust = 1) +
  geom_text(data = . %>% 
              filter(model == "Mouse", comparison == "Down") %>% 
              select(pathogen, model, comparison, timepoint_comparison,pr_auc ) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, pr_auc),
                color = model,
                x = 1,
                y = 0.3),
            size = 2,
            hjust = 1) +
  #Immune
  geom_text(data = . %>% 
              filter(model == "Immune", comparison == "Up") %>% 
              select(pathogen, model, comparison, timepoint_comparison, pr_auc) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, pr_auc),
                color = model,
                x = 1,
                y = 0.2),
            size = 2,
            hjust = 1) +
   geom_text(data = . %>% 
              filter(model == "Immune", comparison == "Down") %>% 
              select(pathogen, model, comparison, timepoint_comparison,pr_auc ) %>% 
              distinct(),
            mapping = aes(label = paste(comparison, pr_auc),
                color = model,
                x = 1,
                y = 0.1),
            size = 2,
            hjust = 1) +
  scale_linetype_manual(values = c("Up" = 1,
                                   "Down" = 2)) +
  # coord_equal() +
  scale_color_manual(values = colors$organism) +
  labs(
  x = "Recall",
  y = "Precision",
  color = "Model",
  linetype = "Comparison") + 
  guides(fill = guide_legend(override.aes = list(size = 4)),
         color = guide_legend(override.aes = list(linewidth = 4, shape = 1))
         ) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
          axis.title.x = element_text(size = 8),
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5),
          strip.text.x = element_text(angle = 0, hjust = 0., vjust = 0.5, size = 8),
          legend.position = "top",
          legend.direction = "horizontal", 
          legend.text = element_text(size = 8, hjust = 0),
          legend.title = element_text(size = 8),
          legend.spacing.x = unit(0, 'cm'),
          legend.spacing.y = unit(0, 'cm'),
          ggh4x.facet.nestline = element_line(colour = "black", linetype = 1),
          legend.box.spacing = unit(0, "cm"),
          panel.spacing.y = unit(0, "lines"), 
          panel.spacing.x = unit(1, "lines"), 
          plot.margin = margin(0, 0.3, 0, 0, unit = "cm"),
          
          ) +
  scale_x_continuous(n.breaks = 3) +
  scale_y_continuous(n.break = 3) +
  guides(linetype = guide_legend(override.aes = list(linewidth = 0.5, size = 1),
                                 order = 2), 
         fill = "none",
         color = guide_legend(override.aes = list(linewidth = 3)))

pr_curve_plot


# pr_curve_plot %>%
#   ggsave(filename = here("Figures", paste0(filename, "_performance_pr_", gene_set_filename, ".png")),
#          width = 8,
#          height = 5)
```


PR-AUC as dotplots

PR-AUC as lineplots
```{r fig.height=3, fig.width=8}

#Get n genes
ngenes = bind_rows(
  classified_df_probs_up %>%
    filter(pred == "up") %>% 
  group_by(pathogen, timepoint_comparison, model) %>% 
  summarise(n_genes = n(),
            comparison = "Up") %>% 
    ungroup(),
  classified_df_probs_down %>%
    filter(pred == "down") %>% 
  group_by(pathogen, timepoint_comparison, model) %>% 
  summarise(n_genes = n(),
            comparison = "Down") %>% 
    ungroup(),
)


# Visualize AUC
pr_auc_df <- bind_rows(pr_auc_results_up,
                      pr_auc_results_down) %>%
  inner_join(ngenes, by = join_by(comparison, pathogen, timepoint_comparison, model)) %>% 
  mutate(model = fct_relevel(model, "Human", "Mouse", "Immune", "Permutation", "DMD", "FIT"),
         comparison = fct_relevel(comparison, "Up", "Down"),
         # timepoint = str_replace(timepoint, "Early hours", "Early\nhours"),
         # timepoint = fct_relevel(timepoint, c("Early\nhours", "2h", "4h", "6h", "12h", "24h", "Day 1", "Day 3", "Day 7")),
         pathogen = case_when(pathogen == "Hepatitis B" ~ "HepB",
                              pathogen == "Staphylococcus aureus" ~ "S. aureus",
                              pathogen == "Escherichia coli" ~ "E. coli",
                              T ~ pathogen),
         pathogen = fct_relevel(pathogen, "Influenza", "HepB", "S. aureus", "E. coli", "Burn", "Trauma"),
         treatment = case_when(pathogen %in% c("HepB", "Influenza") ~ "Vaccination",
                               pathogen %in% c( "S. aureus", "E. coli") ~ "Infection",
                               pathogen %in% c( "Burn", "Trauma") ~ "Injury",
                               T ~ pathogen),
         treatment = fct_relevel(treatment, "Vaccination", "Infection", "Injury")
         ) 

pr_auc_heatmap = pr_auc_df %>% 
  ggplot() +
   aes(x = comparison,
      y = model %>% fct_rev(),
      fill = pr_auc,
      color = model %>% fct_rev(),
      group = model %>% fct_rev()) + 
  
  facet_nested_wrap(~treatment+pathogen+timepoint_comparison,
                    # scales = "free",
                    nrow = 1,
                    strip = strip_nested(size = "variable")
                    ) +
  
  geom_tile(color = "black",
             stroke = 0.5) + 
  
  #Add labels
  geom_text(aes(label = round(pr_auc, 2)), size = 3,
             color = "black",
             fontface = "bold",
             vjust = 0.25,
            data = . %>% filter(pr_auc <= 0.7)) +
  geom_text(aes(label = round(pr_auc, 2)), size = 3,
             color = "white",
             fontface = "bold",
             vjust = 0.25,
            data = . %>% filter(pr_auc > 0.7)) +
   geom_text(aes(label = paste0("n=", n_genes)), size = 2,
             color = "black",
             vjust = 2,
             data = . %>% filter(pr_auc <= 0.7)) +
  
   geom_text(aes(label = paste0("n=", n_genes)), size = 2,
             color = "white",
             vjust = 2,
             data = . %>% filter(pr_auc > 0.7)) +
 

  scale_x_discrete(expand = c(0.05, 0.05)) +
  # scale_y_continuous(expand = c(0.01, 0.01)) +
  theme_vaxgo() +
    scale_fill_gradientn(
        colors = c("white", "#4DBBD5FF","#4361ee"),
        values = scales::rescale(seq(0, 1, length.out = 10)),
        limits = c(0, 1),
        name = "PR_AUC",
        guide = guide_colorbar(
          barwidth = 15,
          barheight = 1,
          nbin = 10,
          raster = FALSE
        )
      ) +
  labs(
    x = "Comparison",
    y = "Model",
    fill = "PR-AUC",
  ) +
    theme(axis.text.x = element_text(angle = 0,  hjust = 0.5, vjust = 1, size = 8),
          axis.text.y = element_text(size = 8, hjust = 1),
          axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          strip.text = element_text(size = 8, margin = margin(1, 0, 1, 0)),
          strip.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, size = 8),
          strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5, size = 8),
          panel.spacing = unit(1, "lines"),
          plot.margin = margin(0, 0.5, 0, 0, unit = "cm"),
          legend.position = "top",
          legend.direction = "horizontal",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-10,0),
          legend.text = element_text(size = 8, hjust = 0),
          legend.title = element_text(size = 8),
          ggh4x.facet.nestline = element_line(colour = "black", linetype = 1, size = 0.5)
    ) 

pr_auc_heatmap
  

pr_auc_heatmap %>%
  ggsave(filename = here("Figures", "all_human_mouse_performance_pr_auc_heatmap_All_OnlyImmune.png"),
         width = 8,
         height = 3)

```



PR-AUC as lineplots
```{r fig.height=12, fig.width=3}


pr_auc_lineplot = pr_auc_df %>% 
  ggplot() +
   aes(x = timepoint_comparison,
      y = pr_auc,
      fill = model,
      color = model,
      group = model) + 
  
  facet_nested_wrap(~treatment+pathogen+comparison,
                    scales = "free",
                    ncol = 2,
                    strip = strip_nested(size = "variable")
                    ) +
  
  geom_line(width = 1,
            aes(linetype = model)) +
  
  geom_point(size = 2,
             pch = 21,
             color = "black",
             stroke = 0.5) + 
  geom_text_repel(aes(label = n_genes), size = 2) +
  # Add a reference line for random prediction (AUC = 0.5)
    # geom_text_repel(aes(label = auc), 
  #                 size = 2.5, 
  #                 # direction = "y", 
  #                 segment.alpha = 1) +

  scale_x_discrete(expand = c(0.05, 0.05)) +
  # scale_y_continuous(expand = c(0.01, 0.01)) +
  theme_vaxgo() +
  scale_linetype_manual(values = c(
    "Mouse" = 1,
    "Immune" = 1,
    "Human" = 1,
    "Permutation" = 2
    )) +
  scale_fill_manual(values = colors$organism) +
  scale_color_manual(values = colors$organism) +
  labs(
    x = "Time",
    y = "PR-AUC",
    fill = "Model",
    shape = "Model",
  ) +
    theme(axis.text.x = element_text(angle = 0,  hjust = 0.5, vjust = 1, size = 8),
          axis.text.y = element_text(size = 8, hjust = 1),
          axis.title.x = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          strip.text = element_text(size = 8, margin = margin(1, 0, 1, 0)),
          strip.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, size = 8),
          strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5, size = 8),
          panel.spacing = unit(0, "lines"),
          plot.margin = margin(0, 0.5, 0, 0, unit = "cm"),
          legend.position = "top",
          legend.direction = "horizontal",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-10,0),
          legend.text = element_text(size = 8, hjust = 0),
          legend.title = element_text(size = 8),
          ggh4x.facet.nestline = element_line(colour = "black", linetype = 1, size = 0.5)
    ) +
  guides(color = "none",
         shape = "none",
         linetype = "none",
         fill = guide_legend(nrow = 2, by.row = T))

pr_auc_lineplot
# pr_auc_lineplot %>%
#   ggsave(filename = here("Figures", "all_human_mouse_performance_pr_pr_auc_lineplot_All_OnlyImmune.png"),
#          width = 3,
#          height = 12)

```








