---
title: "Machine learning"
author: "Wasim Aluísio Prates-Syed"

output: 
  html_document: 
    toc: TRUE
    toc_depth: 4
    code_folding: hide
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE, cache = TRUE)
```


#Required

```{r}
# install.packages("here")
library(here)
source(here("scripts_notebooks", "required.R"))
```



#Building new models
## Univariate

```{r}


df_mouse = AllData_V2.0_blood %>% 
  clean_names() %>% 
  select(csp_id, mm_entrez, hs_entrez, fc_hs, fc_mm) %>% 
  rownames_to_column("del") %>% 
  select(csp_id, mm_entrez, fc_mm)
  
df_human = AllData_V2.0_blood %>% 
  clean_names() %>% 
  select(csp_id, mm_entrez, hs_entrez, fc_hs, fc_mm) %>% 
  rownames_to_column("del") %>% 
  select(csp_id, hs_entrez, fc_hs)
```






### Single gene


```{r}
X_all <- df_mouse %>%
  pivot_wider(names_from = mm_entrez, values_from = fc_mm) %>%
  arrange(csp_id) %>% 
  select(-csp_id) 

y_target_all <- df_human %>%
  arrange(csp_id) %>% 
  select(csp_id, hs_entrez, fc_hs) %>%
  distinct() %>% 
  pivot_wider(names_from = hs_entrez, values_from = fc_hs) %>% 
  select(-csp_id) 

cor_matrix <- cor(X_all, y_target_all, use = "pairwise.complete.obs")

cor_values = as.data.frame(cor_matrix) %>% 
  rownames_to_column("mm_entrez")


cor_values

```



```{r}
target_gene <- "26119"

X <- df_mouse %>%
  pivot_wider(names_from = mm_entrez, values_from = fc_mm) %>%
  arrange(csp_id)

y_target <- df_human %>%
  filter(hs_entrez == target_gene) %>%
  select(csp_id, fc_hs) %>%
  distinct() %>%
  arrange(csp_id)

full_df <- inner_join(X, y_target, by = "csp_id")  %>% 
  select(csp_id, fc_hs, everything()) %>% 
  mutate(across(where(is.numeric), ~replace_na(., 0)))

train_df = full_df

# Correlation
top_genes <- cor_values %>% 
  select(mm_entrez, target_gene = target_gene) %>%
  slice_max(abs(target_gene), n = 100) %>% 
  pull(mm_entrez)

train_df <- full_df %>%
  select(all_of(c("csp_id", "fc_hs", top_genes))) %>%
  mutate(across(where(is.numeric), ~replace_na(., 0)))

# Split into train and test
set.seed(123)
data_split <- initial_split(train_df, prop = 0.8)
train_data <- training(data_split)
test_data <- testing(data_split)
train_folds <- vfold_cv(train_data, repeats = 5)

# Recipe
rec <- recipe(fc_hs ~ ., data = train_data) %>%
  update_role(csp_id, new_role = "id") %>%
  step_normalize(all_predictors())
```



```{r}
rf_model <- rand_forest(mtry = tune(), trees = 500) %>%
  set_engine("ranger", importance = "permutation") %>%
  set_mode("regression")

wf <- workflow() %>%
  add_recipe(rec) %>%
  add_model(rf_model)

mer_metrics <- metric_set(yardstick::rmse,
                          yardstick::rsq)


#Cross validation
set.seed(234)
trees_folds <- vfold_cv(train_data, v = 5)

doParallel::registerDoParallel()

rf_tuned <- tune_grid(
  wf,
  metrics = mer_metrics,
  resamples = trees_folds,
  grid = 20
)


# Check
rf_tuned %>%
  collect_metrics() %>%
  ggplot()+
  aes(x = mtry, y = mean, colour = .metric, label = mtry) +
  geom_line() +
  geom_label() +
  scale_color_npg()+
  theme_vaxgo() +
  theme(axis.text.x = element_text(color = "black", size = 12)) +
  facet_wrap(vars(.metric), scales = "free")

best_model <- select_best(rf_tuned, metric = "rmse")

# 6. Finalizar e avaliar
final_wf <- finalize_workflow(wf, best_model)
final_fit <- fit(final_wf, train_data)

preds <- predict(final_fit, test_data) %>%
  bind_cols(test_data)

metrics(preds, truth = fc_hs, estimate = .pred)


# Extraia o modelo ajustado diretamente
final_model <- extract_fit_parsnip(final_fit)$fit

library(vip)
# Gere o gráfico de importância
vip(final_model, num_features = 20)

vip_df <- vi(final_model) %>%
  arrange(desc(Importance)) %>% 
  mutate(hs_entrez = target_gene)

head(vip_df, 10)

```



##### Lasso regression
```{r}
# Modelo LASSO
lasso_model <- linear_reg(penalty = tune(), mixture = 1) %>%  # mixture = 1 → LASSO
  set_engine("glmnet") %>%
  set_mode("regression")

# Workflow
wf <- workflow() %>%
  add_recipe(rec) %>%
  add_model(lasso_model)

# Cross-validation
set.seed(234)
lasso_folds <- vfold_cv(train_data, v = 5)

# Grid de valores de lambda
lambda_grid <- grid_regular(penalty(range = c(-4, 0)), levels = 20)  # log10 scale

# Métricas
mer_metrics <- metric_set(rmse, rsq)

# Tuning
lasso_tuned <- tune_grid(
  wf,
  resamples = lasso_folds,
  metrics = mer_metrics,
  grid = lambda_grid
)

# Selecionar melhor modelo
best_model <- select_best(lasso_tuned, metric = "rmse")


# Check
lasso_tuned %>%
  collect_metrics() %>%
  ggplot()+
  aes(x = penalty, y = mean, colour = .metric, label = penalty) +
  geom_line() +
  geom_label() +
  scale_color_npg()+
  theme_vaxgo() +
  theme(axis.text.x = element_text(color = "black", size = 12)) +
  facet_wrap(vars(.metric), scales = "free")


# Extrair métricas
best_metrics <- lasso_tuned %>%
  collect_metrics() %>%
  filter(penalty == best_model$penalty)

rmse_val <- best_metrics %>% filter(.metric == "rmse") %>% pull(mean)
rsq_val  <- best_metrics %>% filter(.metric == "rsq")  %>% pull(mean)

# Finalizar e ajustar o modelo
final_wf <- finalize_workflow(wf, best_model)
final_fit <- fit(final_wf, train_data)
final_model <- extract_fit_parsnip(final_fit)$fit


# Gere o gráfico de importância
library(vip)
vip(final_model, num_features = 20)

vip_df <- vi(final_model) %>%
  arrange(desc(Importance)) %>% 
  mutate(hs_entrez = target_gene)

vip_df %>% 
inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(hs_entrez = human_entrez,
                      hgnc_symbol) %>% 
               mutate(hs_entrez = as.character(hs_entrez)), 
             by = "hs_entrez") %>% 
  rename(mm_entrez = Variable) %>% 
  inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(mm_entrez = mouse_ortholog,
                      mm_symbol = mgi_symbol) %>% 
               mutate(mm_entrez = as.character(mm_entrez)), 
             by = "mm_entrez") %>% 
  select(hgnc_symbol, hs_entrez, Importance, mm_symbol, mm_entrez) %>% 
  filter(Importance > 0.01)


```
#### Worflowset

```{r}
# install.packages("rules")
# install.packages("baguette")
library(rules)
library(baguette)
install.packages("kernlab")



lasso_spec <- linear_reg(penalty = tune(), mixture = 1) %>%  # mixture = 1 → LASSO
  set_engine("glmnet") %>%
  set_mode("regression")

rf_spec <- 
   rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
   set_engine("ranger") %>% 
   set_mode("regression")

nnet_spec <-
   mlp(hidden_units = tune(), penalty = tune(), epochs = tune()) %>%
   set_engine("nnet", MaxNWts = 2600) %>%
   set_mode("regression")

nnet_param <-
   nnet_spec %>%
   extract_parameter_set_dials() %>%
   update(hidden_units = hidden_units(c(1, 27)))


# linear_reg_spec <- 
#    linear_reg(penalty = tune(), mixture = tune()) %>% 
#    set_engine("glmnet")

# mars_spec <- 
#    mars(prod_degree = tune()) %>%  #<- use GCV to choose terms
#    set_engine("earth") %>% 
#    set_mode("regression")
# 
# svm_r_spec <- 
#    svm_rbf(cost = tune(), rbf_sigma = tune()) %>% 
#    set_engine("kernlab") %>% 
#    set_mode("regression")
# 
# svm_p_spec <- 
#    svm_poly(cost = tune(), degree = tune()) %>% 
#    set_engine("kernlab") %>% 
#    set_mode("regression")
# 
# knn_spec <- 
#    nearest_neighbor(neighbors = tune(), dist_power = tune(), weight_func = tune()) %>% 
#    set_engine("kknn") %>% 
#    set_mode("regression")

# cart_spec <- 
#    decision_tree(cost_complexity = tune(), min_n = tune()) %>% 
#    set_engine("rpart") %>% 
#    set_mode("regression")

# bag_cart_spec <- 
#    bag_tree() %>% 
#    set_engine("rpart", times = 50L) %>% 
#    set_mode("regression")

# xgb_spec <- 
#    boost_tree(tree_depth = tune(), learn_rate = tune(), loss_reduction = tune(), 
#               min_n = tune(), sample_size = tune(), trees = tune()) %>% 
#    set_engine("xgboost") %>% 
#    set_mode("regression")
# 
# cubist_spec <- 
#    cubist_rules(committees = tune(), neighbors = tune()) %>% 
#    set_engine("Cubist") 

#### Create workflowset
workflow.set1 <- 
   workflow_set(
      preproc = list(rec = rec), 
      models = list(
        # linear = linear_reg_spec,
                    RForest = rf_spec,
                    Lasso = lasso_spec,
                    # KNN = knn_spec, 
                    neural_network = nnet_spec
                    )
   ) %>% 
  option_add(param_info = nnet_param,
           id = "normalized_neural_network")

workflow.set1


#Tune hyperparameters
grid_ctrl <-
   control_grid(
      save_pred = TRUE,
      parallel_over = "everything",
      save_workflow = TRUE
   )

grid_results <-
   workflow.set1 %>%
   workflow_map(
      seed = 1503,
      resamples = train_folds,
      grid = 5,
      control = grid_ctrl
   )

grid_results
```


```{r}
#Get metrics
grid_results %>% 
   rank_results() %>% 
   filter(.metric == "rmse") %>% 
   select(model, .config, rmse = mean, rank)

autoplot(
   grid_results,
   rank_metric = "rmse",  # <- how to order models
   metric = "rmse",       # <- which metric to visualize
   select_best = TRUE     # <- one point per workflow
) +
   theme(legend.position = "right")

#Get results for specific model
autoplot(grid_results, id = "rec_Lasso", metric = "rmse") +
  geom_line(aes(group = id, color = id)) +
  geom_point(aes(color = id))
autoplot(grid_results, id = "rec_RForest", metric = "rmse") +
  geom_line(aes(group = id, color = id)) +
  geom_point(aes(color = id))
autoplot(grid_results, id = "rec_neural_network", metric = "rmse") +
  geom_line(aes(group = id, color = id)) +
  geom_point(aes(color = id))
```

Fine tune
```{r}
#Fine tune
library(finetune)

race_ctrl <-
   control_race(
      save_pred = TRUE,
      parallel_over = "everything",
      save_workflow = TRUE
   )

#Analyze
race_results <-
   workflow.set1 %>%
   workflow_map(
      "tune_race_anova",
      seed = 1503,
      resamples = train_folds,
      grid = 5,
      control = race_ctrl
   )

autoplot(
   race_results,
   rank_metric = "rmse",  
   metric = "rmse",       
   select_best = TRUE    
) +
   theme(legend.position = "right")

matched_results <- 
   rank_results(race_results, select_best = TRUE) %>% 
   select(wflow_id, .metric, race = mean, config_race = .config) %>% 
   inner_join(
      rank_results(grid_results, select_best = TRUE) %>% 
         select(wflow_id, .metric, complete = mean, 
                config_complete = .config, model),
      by = c("wflow_id", ".metric"),
   ) %>%  
   filter(.metric == "rmse")

library(ggrepel)

matched_results %>% 
   ggplot(aes(x = complete, y = race)) + 
   geom_abline(lty = 3) + 
   geom_point() + 
   geom_text_repel(aes(label = model)) +
   coord_obs_pred() + 
   labs(x = "Complete Grid RMSE", y = "Racing RMSE")
```

Finalize model
```{r}
#Finalize model
best_results <- 
   race_results %>% 
   extract_workflow_set_result("rec_RForest") %>% 
   select_best(metric = "rmse")
best_results

boosting_test_results <- 
   race_results %>% 
   extract_workflow("rec_RForest") %>% 
   finalize_workflow(best_results) %>% 
   last_fit(split = data_split)

collect_metrics(boosting_test_results)

boosting_test_results %>% 
   collect_predictions() %>% 
   ggplot(aes(x = fc_hs, y = .pred)) + 
   geom_abline(color = "gray50", lty = 2) + 
   geom_point(alpha = 0.5) + 
   coord_obs_pred() + 
   labs(x = "observed", y = "predicted")
```




### Multiple genes


#### Random forest
```{r}
library(tidymodels)
library(vip)
library(dplyr)
library(tidyr)
library(purrr)

model_rf_by_gene <- function(target_gene, df_mouse, df_human, top_n = 50) {
  
  rf_model <- rand_forest(mtry = tune(), trees = 500) %>%
    set_engine("ranger", importance = "permutation") %>%
    set_mode("regression")
  
  wf <- workflow() %>%
    add_recipe(rec) %>%
    add_model(rf_model)
  
  # CV
  set.seed(234)
  trees_folds <- vfold_cv(train_data, v = 5)
  mer_metrics <- metric_set(rmse, rsq)
  
  rf_tuned <- tune_grid(
    wf,
    metrics = mer_metrics,
    resamples = trees_folds,
    grid = 5
  )
  
  best_model <- select_best(rf_tuned, metric = "rmse")
  
  # Extraia os valores de RMSE e RSQ do melhor modelo
  best_metrics <- rf_tuned %>%
    collect_metrics() %>%
    filter(mtry == best_model$mtry)
  
  rmse_val <- best_metrics %>% filter(.metric == "rmse") %>% pull(mean)
  rsq_val  <- best_metrics %>% filter(.metric == "rsq")  %>% pull(mean)
  
  final_wf   <- finalize_workflow(wf, best_model)
  final_fit  <- fit(final_wf, train_data)
  final_model <- extract_fit_parsnip(final_fit)$fit
  
  preds <- predict(final_fit, test_data) %>%
  bind_cols(test_data)
  
  metrics_pred = metrics(preds, truth = fc_hs, estimate = .pred)
  
  
  # VIP com métricas adicionadas
  vi(final_model) %>%
    arrange(desc(Importance)) %>%
    mutate(hs_entrez = target_gene,
           rmse = rmse_val,
           rsq = rsq_val)
  
  
  vip_df <- vi(final_model) %>%
  arrange(desc(Importance)) %>% 
  mutate(hs_entrez = target_gene)
  
  results = vip_df %>% inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(hs_entrez = human_entrez,
                      hgnc_symbol) %>% 
               mutate(hs_entrez = as.character(hs_entrez)), 
             by = "hs_entrez") %>% 
  rename(mm_entrez = Variable) %>% 
  inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(mm_entrez = mouse_ortholog,
                      mm_symbol = mgi_symbol) %>% 
               mutate(mm_entrez = as.character(mm_entrez)), 
             by = "mm_entrez") %>% 
  select(hgnc_symbol, hs_entrez, Importance, mm_symbol, mm_entrez)  %>% 
    arrange(-Importance)
  results
  preds
  metrics_pred
}
```

```{r}
# Lista de genes-alvo
# target_genes <- unique(df_human$hs_entrez)[1:3]  # ou outra seleção
HS_MM_Symbol_Entrez = FIT.mouse2man::HS_MM_Symbol_Entrez

target_genes = HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               rename(hs_entrez = human_entrez) %>% 
               mutate(hs_entrez = as.character(hs_entrez)) %>% 
  filter(hgnc_symbol %in% c("TLR8")) %>%
  pull(hs_entrez) %>% 
  unique()

# Rodar para vários genes
vip_all_rf <- map_df(target_genes, 
                  model_rf_by_gene, 
                  # X =
                  df_mouse = df_mouse, 
                  df_human = df_human, 
                  top_n = 5)

vip_all_rf$rmse %>% unique()
vip_all_rf$rsq %>% unique()

vip_all_rf %>% 
  inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(hs_entrez = human_entrez,
                      hgnc_symbol) %>% 
               mutate(hs_entrez = as.character(hs_entrez)), 
             by = "hs_entrez") %>% 
  rename(mm_entrez = Variable) %>% 
  inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(mm_entrez = mouse_ortholog,
                      mm_symbol = mgi_symbol) %>% 
               mutate(mm_entrez = as.character(mm_entrez)), 
             by = "mm_entrez") %>% 
  select(hgnc_symbol, hs_entrez, Importance, mm_symbol, mm_entrez)

```

#### Lasso

```{r}
library(tidymodels)
library(dplyr)
library(tidyr)
library(purrr)
library(tibble)


model_lasso_by_gene <- function(target_gene, X, df_human, top_n = 50, cor_values) {

  y_target <- df_human %>%
    filter(hs_entrez == target_gene) %>%
    select(csp_id, fc_hs) %>%
    distinct() %>%
    arrange(csp_id)

  full_df <- inner_join(X, y_target, by = "csp_id") %>%
    select(csp_id, fc_hs, everything()) %>%
    mutate(across(where(is.numeric), ~replace_na(., 0)))

  if (nrow(full_df) < 10) return(NULL)  # ignora se poucos dados

  top_genes <- cor_values %>% 
  select(mm_entrez, target_gene = target_gene) %>%
  slice_max(abs(target_gene), n = 50) %>% 
  pull(mm_entrez)


  train_df <- full_df %>%
    select(all_of(c("csp_id", "fc_hs", top_genes))) %>%
    mutate(across(where(is.numeric), ~replace_na(., 0)))

  # Split
  set.seed(123)
  data_split <- initial_split(train_df, prop = 0.8)
  train_data <- training(data_split)
  test_data  <- testing(data_split)

  rec <- recipe(fc_hs ~ ., data = train_data) %>%
    update_role(csp_id, new_role = "id") %>%
    step_normalize(all_predictors())

  # Modelo LASSO
  lasso_model <- linear_reg(penalty = tune(), mixture = 1) %>%
    set_engine("glmnet") %>%
    set_mode("regression")

  wf <- workflow() %>%
    add_recipe(rec) %>%
    add_model(lasso_model)

  set.seed(234)
  lasso_folds <- vfold_cv(train_data, v = 5)

  lambda_grid <- grid_regular(penalty(range = c(-4, 0)), levels = 20)

  mer_metrics <- metric_set(rmse, rsq)

  lasso_tuned <- tune_grid(
    wf,
    resamples = lasso_folds,
    metrics = mer_metrics,
    grid = lambda_grid
  )

  best_model <- select_best(lasso_tuned, metric = "rmse")

  best_metrics <- lasso_tuned %>%
    collect_metrics() %>%
    filter(penalty == best_model$penalty)

  rmse_val <- best_metrics %>% filter(.metric == "rmse") %>% pull(mean)

  final_wf <- finalize_workflow(wf, best_model)
  final_fit <- fit(final_wf, train_data)
  final_model <- extract_fit_parsnip(final_fit)$fit
  
  
  preds <- predict(final_fit, test_data) %>%
  bind_cols(test_data)
  
  metrics_pred = metrics(preds, truth = fc_hs, estimate = .pred)
  
  
  results = vip_df <- vi(final_model) %>%
  arrange(desc(Importance)) %>% 
  mutate(hs_entrez = target_gene) %>% 
inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(hs_entrez = human_entrez,
                      hgnc_symbol) %>% 
               mutate(hs_entrez = as.character(hs_entrez)), 
             by = "hs_entrez") %>% 
  rename(mm_entrez = Variable) %>% 
  inner_join(HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               select(mm_entrez = mouse_ortholog,
                      mm_symbol = mgi_symbol) %>% 
               mutate(mm_entrez = as.character(mm_entrez)), 
             by = "mm_entrez") %>% 
  select(hgnc_symbol, hs_entrez, Importance, mm_symbol, mm_entrez) 

return(list(
    results = results,
    metrics_pred = metrics_pred,
    preds = preds
  ))
}

```


```{r}
# X <- df_mouse %>%
#     pivot_wider(names_from = mm_entrez, values_from = fc_mm) %>%
#     arrange(csp_id)
# 
# 
# cor_matrix <- cor(X_all, y_target_all, use = "pairwise.complete.obs")
# 
# cor_values = as.data.frame(cor_matrix) %>% 
#   rownames_to_column("mm_entrez")



# Lista de genes-alvo
# target_genes <- unique(df_human$hs_entrez)[1:3]  # ou outra seleção
HS_MM_Symbol_Entrez = FIT.mouse2man::HS_MM_Symbol_Entrez

target_genes = HS_MM_Symbol_Entrez %>% 
               clean_names() %>% 
               rename(hs_entrez = human_entrez) %>% 
               mutate(hs_entrez = as.character(hs_entrez)) %>% 
  filter(hgnc_symbol %in% c("TLR8")) %>%
  pull(hs_entrez) %>% 
  unique()

# Rodar para vários genes
vip_all_lasso <- map_df(target_genes, 
                  model_lasso_by_gene, 
                  X = X, 
                  cor_values = cor_values,
                  df_human = df_human, 
                  top_n = 5)

vip_all_rf$rmse %>% unique()
vip_all_rf$rsq %>% unique()

vip_all_lasso %>% 
  filter(Importance > 0.000000)


```












### Genes
```{r}
library(matrixStats)

df_mouse = AllData_V2.0_blood %>% 
  clean_names() %>% 
  select(csp_id, mm_entrez, hs_entrez, fc_hs, fc_mm) %>% 
  rownames_to_column("del") %>% 
  select(csp_id, hs_entrez, fc_mm) %>% 
  pivot_wider(names_from = "hs_entrez",
              values_from = "fc_mm") %>% 
  mutate(across(where(is.numeric), ~replace_na(.x, 0))) %>% 
  as.tibble() %>% 
  column_to_rownames("csp_id")  
  
  
df_human = AllData_V2.0_blood %>% 
  clean_names() %>% 
  select(csp_id, mm_entrez, hs_entrez, fc_hs, fc_mm) %>% 
  rownames_to_column("del") %>% 
  select(csp_id, hs_entrez, fc_hs) %>% 
  pivot_wider(names_from = "hs_entrez",
              values_from = "fc_hs") %>% 
  mutate(across(where(is.numeric), ~replace_na(.x, 0))) %>% 
  as.tibble() %>% 
  column_to_rownames("csp_id")


#Reduce number of genes
variancias_m <- colVars(as.matrix(df_mouse))
variancias_h <- colVars(as.matrix(df_human))

ggplot(data.frame(variancia = variancias_h), aes(x = variancia)) +
  geom_histogram(bins = 100, fill = "skyblue", alpha = 0.7) +
  geom_vline(xintercept = 0.05, color = "darkred", linetype = "dashed") +
  labs(title = "Distribuição da Variância dos Genes",
       x = "Variância", y = "Número de Genes") +
  theme_minimal()


ggplot(data.frame(variancia = variancias_m), aes(x = variancia)) +
  geom_histogram(bins = 100, fill = "skyblue", alpha = 0.7) +
  geom_vline(xintercept = 0.01, color = "darkred", linetype = "dashed") +
  labs(title = "Distribuição da Variância dos Genes",
       x = "Variância", y = "Número de Genes") +
  theme_minimal()

mean(variancias_m > 0.01) 
mean(variancias_h > 0.01) 


# Filtrar apenas df_mouse
variancias_mouse <- apply(df_mouse, 2, var, na.rm = TRUE)
# cutoff_mouse <- quantile(variancias_mouse, probs = 0.30)  # manter 63%
# top_genes <- names(variancias_mouse[variancias_mouse > cutoff_mouse])
#Keep only the 3000 most variable genes
top_genes <- names(sort(variancias_mouse, decreasing = TRUE))[1:3000]

# Aplicar o mesmo subconjunto aos humanos
df_mouse_final <- df_mouse[, top_genes]
df_human_final <- df_human[, top_genes]


# Filter by correlation
cor_genes <- map_dbl(colnames(df_mouse), function(gene) {
  cor(df_mouse[[gene]], df_human[[gene]], use = "complete.obs")
})
names(cor_genes) <- colnames(df_mouse)
genes_filtered_corr <- names(cor_genes)[abs(cor_genes) > 0.75]

# Filtrar os dataframes mantendo somente os genes selecionados
df_mouse_filtered <- df_mouse[, genes_filtered_corr]
df_human_filtered <- df_human[, genes_filtered_corr]

# Conferir dimensões
dim(df_mouse_filtered)
dim(df_human_filtered)
length(genes_filtered_corr)
dim(df_mouse)
dim(df_mouse_filtered)
dim(df_mouse_final)
dim(df_human)
dim(df_human_filtered)
dim(df_human_final)

#As matrix
df_human.matrix = as.matrix(df_human_filtered)
df_mouse.matrix = as.matrix(df_mouse_filtered)

fit <- glmnet(
  x = df_mouse.matrix,
  y = df_human.matrix,
  family = "mgaussian",
  alpha = 1  # alpha=1 para LASSO, alpha=0 para ridge, 0<alpha<1 para elastic net 
)

# Para visualizar os coeficientes de diferentes valores de lambda
print(fit)

```












