---
title: "Exploring other datasets"
author: "Wasim Aluísio Prates-Syed"
date: "2025-07-23"
output: 
  html_document: 
    toc: TRUE
    toc_depth: 4
    code_folding: hide
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE, cache = TRUE)
```


# Exploring other datasets

##Import required codes
```{r}
# install.packages("here")
library(here)
source(here("scripts_notebooks", "required.R"))
```

## Found in translation
Ref: Normand, R., Du, W., Briller, M. et al. Found In Translation: a machine learning model for mouse-to-human inference. Nat Methods 15, 1067–1073 (2018). https://doi.org/10.1038/s41592-018-0214-9
Github: https://github.com/shenorrLabTRDF/FIT.mouse2man 
```{r}
#Install model package
# library(devtools)
# devtools::install_github('shenorrLabTRDF/FIT.mouse2man')
library(FIT.mouse2man)

#Import files
pca_rotations = FIT.mouse2man::pca_rotations
best_models = FIT.mouse2man::best_models
HS_MM_Symbol_Entrez = FIT.mouse2man::HS_MM_Symbol_Entrez %>% 
  rename(human_symbol = HGNC_symbol,
         mouse_symbol =MGI.symbol,
         HS.Entrez = Human.Entrez,
         MM.Entrez = Mouse.Ortholog)
MM_Entrez_symbol_desc = FIT.mouse2man::MM_Entrez_symbol_desc
slopes_per_gene_V2.0 = FIT.mouse2man::slopes_per_gene_V2.0
# Psoriasis_classifier_neg = FIT.mouse2man::Psoriasis_classifier_neg
# StaphInfection_classifier_pos = FIT.mouse2man::StaphInfection_classifier_pos

#Training data
AllData_V2.0 = FIT.mouse2man::AllData_V2.0 %>% 
  inner_join(HS_MM_Symbol_Entrez, 
             by )
  


```


## Filter datasets
```{r}
#Get metadata for datasets on Supplementary Files of FIT paper and filter datasets with blood-derived samples
training_datasets_blood <- c(
  "Microarrays_RF_EcoliInfection_1",
  "Microarrays_RF_EcoliInfection_3",
  "Microarrays_RF_StaphInfection_10",
  "Microarrays_RF_StaphInfection_11",
  "Microarrays_RF_StaphInfection_12",
  "Microarrays_RF_StaphInfection_1",
  "Microarrays_RF_StaphInfection_2",
  "Microarrays_RF_StaphInfection_3",
  "Microarrays_RF_StaphInfection_4",
  "Microarrays_RF_StaphInfection_5",
  "Microarrays_RF_StaphInfection_6",
  "Microarrays_RF_StaphInfection_7",
  "Microarrays_RF_StaphInfection_8",
  "Microarrays_RF_StaphInfection_9",
  "Microarrays_ST_Burns_1",
  "Microarrays_ST_Burns_2",
  "Microarrays_ST_Burns_3",
  "Microarrays_ST_Injury_1",
  "Microarrays_ST_Injury_3",
  "Microarrays_ST_Injury_4",
  "Microarrays_ST_Injury_5",
  "Microarrays_ST_Sepsis_10",
  "Microarrays_ST_Sepsis_14",
  "Microarrays_ST_Sepsis_16",
  "Microarrays_ST_Sepsis_17",
  "Microarrays_ST_Sepsis_18",
  "Microarrays_ST_Sepsis_19",
  "Microarrays_ST_Sepsis_20",
  "Microarrays_ST_Sepsis_2",
  "Microarrays_ST_Sepsis_3",
  "Microarrays_ST_Sepsis_4",
  "Microarrays_ST_Sepsis_5",
  "Microarrays_ST_Sepsis_6",
  "Microarrays_ST_Sepsis_9"
)

AllData_V2.0_blood = AllData_V2.0 %>% 
  filter(CSP_ID %in% c(training_datasets_blood))

#Save
AllData_V2.0_blood %>% 
  saveRDS(here("new_models", "AllData_FIT_training_blood.rds"))
```

Import
```{r}
AllData_V2.0_blood = read_rds(here("new_models", "AllData_FIT_training_blood.rds"))
```

### Plot distributions
```{r fig.height=8, fig.width=10}
AllData_V2.0_distributions_plot = AllData_V2.0 %>% 
  clean_names() %>% 
  pivot_longer(cols = c(fc_hs:qval_mm),
               names_to = "metric",
               values_to = "value") %>% 
  mutate(organism = if_else(str_detect(metric, "mm"),"Mouse", "Human")) %>% 
  filter(metric %in% c("fc_hs", "fc_mm")) %>% 
  mutate(metric = if_else(str_detect(metric, "fc"), "fc", metric)) %>% 
  ggplot() +
  aes(x = value, fill = organism) +
  geom_histogram( position = position_identity(), alpha = 0.5, bins = 50) +
  facet_wrap(~disease, 
             scale = "free_y", axes = "all" 
             # strip.position="right"
             ) +
  scale_y_continuous(expand = c(0.01, 0.01), n.breaks = 3) +
  scale_x_continuous(limits = c(-2, 2)) +
    scale_fill_manual(
  values = c(
    FIT = "#CE1800FF", 
    Mouse = "#546E7AFF",
    Human = "#4DBBD5FF"))+
    scale_color_manual(
  values = c(
    FIT = "#CE1800FF", 
    Mouse = "#546E7AFF",
    Human = "#4DBBD5FF"))+
    theme_vaxgo() +
  theme(axis.text.x = element_text(angle = 0),
        legend.position = "top",
        strip.text.x = element_text(color = "black", size = 10),
        strip.text.y = element_text(color = "black", angle = 0, hjust = 0), 
        panel.spacing.y = unit(0.8, "lines"),
        strip.background.y = element_rect(fill = NA, color = NA)) +
  labs(fill = "Organism",
       color = "Organism",
       x = "Log2-fold change",
       y = "Frequency",
       title = "All samples")


AllData_V2.0_distributions_plot 

AllData_V2.0_blood_distributions_plot = AllData_V2.0_blood %>% 
  clean_names() %>% 
  pivot_longer(cols = c(fc_hs:qval_mm),
               names_to = "metric",
               values_to = "value") %>% 
  mutate(organism = if_else(str_detect(metric, "mm"),"Mouse", "Human")) %>% 
  filter(metric %in% c("fc_hs", "fc_mm")) %>% 
  mutate(metric = if_else(str_detect(metric, "fc"), "fc", metric)) %>% 
  ggplot() +
  aes(x = value, fill = organism) +
  geom_histogram( position = position_identity(), alpha = 0.5, bins = 50) +
  facet_wrap(~disease, 
             scale = "free_y", axes = "all",
             ncol = 1
             # strip.position="right"
             ) +
  scale_y_continuous(expand = c(0.01, 0.01), n.breaks = 3) +
  scale_x_continuous(limits = c(-2, 2)) +
    scale_fill_manual(
  values = c(
    FIT = "#CE1800FF", 
    Mouse = "#546E7AFF",
    Human = "#4DBBD5FF"))+
    scale_color_manual(
  values = c(
    FIT = "#CE1800FF", 
    Mouse = "#546E7AFF",
    Human = "#4DBBD5FF"))+
    theme_vaxgo() +
  theme(axis.text.x = element_text(angle = 0),
        legend.position = "top",
        strip.text.x = element_text(color = "black", size = 10),
        strip.text.y = element_text(color = "black", angle = 0, hjust = 0), 
        panel.spacing.y = unit(0.8, "lines"),
        plot.margin = margin(0.5, 1, 0.2, 1, "cm"),
        strip.background.y = element_rect(fill = NA, color = NA)) +
  labs(fill = "Organism",
       color = "Organism",
       x = "Log2-fold change",
       y = "Frequency",
       title = "Blood samples")


AllData_V2.0_blood_distributions_plot 
  
```
Plot all
```{r fig.height=8, fig.width=12}
AllData_V2.0_distributions_plot + AllData_V2.0_blood_distributions_plot +
  plot_layout(widths = c(1, 0.15),
              guides = "collect",
              axes = "collect") +
  plot_annotation(theme = theme(legend.position = "top"))

```






```{r}
AllData_V2.0 %>%
  inner_join(HS_MM_Symbol_Entrez,
             by = join_by())
  ggplot()



```








## Plot correlation
```{r}
cov_genes_FIT_training = AllData_V2.0 %>% 
  clean_names() %>% 
  select(hs_entrez, mean_human = fc_hs, mean_mouse = fc_mm) %>% 
  inner_join(HS_MM_Symbol_Entrez %>%
               clean_names() %>%
               select(human_symbol = hgnc_symbol,
                      hs_entrez = human_entrez) %>% 
               mutate(hs_entrez = as.character(hs_entrez)),
             by = "hs_entrez") %>% 
  arrange(human_symbol) %>% 
  group_by(human_symbol) %>% 
  summarize(sd_human = sd(mean_human),
            cov = cov(mean_human, mean_mouse),
            mean_human_time = mean(mean_human),
            mean_mouse_time = mean(mean_mouse)) %>% 
  arrange(-cov)

cov_genes_FIT_training %>% filter(abs(cov) > 0.001) #15891 genes from 6,373 (92.9%)
cov_genes_FIT_training %>% filter(abs(cov) > 0.01) #11320 genes from 6,373 (50.3%)
cov_genes_FIT_training %>% filter(abs(cov) > 0.1) #1151 genes
cov_genes_FIT_training %>% filter(abs(cov) > 0.2) #356 genes
cov_genes_FIT_training %>% filter(abs(cov) > 0.3) #186 genes


genes_vary_human_all_FIT = cov_genes_FIT_training %>% 
  filter(abs(mean_human_time) >= 0.1,
        abs(mean_mouse_time) <= 0.1) %>% 
  arrange(-abs(cov))

genes_vary_mouse_all_FIT = cov_genes_FIT_training %>% 
  filter(abs(mean_mouse_time) >= 0.1,
                abs(mean_human_time) <= 0.1) %>% 
  arrange(-abs(cov))

genes_vary_human_mouse_all_FIT = cov_genes_FIT_training %>% 
  filter(abs(mean_human_time) >= 0.1,
         abs(mean_mouse_time) >= 0.1) %>% 
  arrange(-abs(cov))

genes_not_vary_human_mouse_all_FIT = cov_genes_FIT_training %>% 
   filter(abs(mean_human_time) <= 0.1, 
          abs(mean_mouse_time) <= 0.1) %>%  
  arrange(-abs(cov))

cov_genes_FIT_training %>% filter(abs(mean_human_time) > 0.1) #3,962
cov_genes_FIT_training %>% filter(abs(mean_human_time) > 0.2) #2191

cov_genes_FIT_training %>% filter(abs(mean_mouse_time) > 0.1) #3363
cov_genes_FIT_training %>% filter(abs(mean_mouse_time) > 0.2) #1631

cov_genes_FIT_training %>% filter(abs(mean_mouse_time) < 0.1) #3,010
cov_genes_FIT_training %>% filter(abs(mean_mouse_time) < 0.2) #4742



genes_vary_human_all_FIT #5,787
genes_vary_mouse_all_FIT #1,807
genes_not_vary_human_mouse_all_FIT #6,476
genes_vary_human_mouse_all_FIT #2,355
```




#Plot 

```{r fig.height=8, fig.width=8}
genes_vary_human = cov_genes_FIT_training %>% 
  ggplot() +
  aes(x = mean_human_time,
      y = mean_mouse_time) +
    geom_point(color = "#3182bd", fill = NA, pch = 21) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  scale_y_continuous(limits = c(-1.5, 1.5)) +
    gghighlight(abs(mean_human_time) >= 0.1,
                abs(mean_mouse_time) <= 0.1,
              use_direct_label = FALSE, 
              unhighlighted_params = list(alpha = 0.2, fill = NA)) +
  geom_label_repel(aes(label = human_symbol), max.overlaps = 20, force_pull = 4, size = 3,
                  data = cov_genes_FIT_training %>% 
                    filter(abs(mean_human_time) > 0.1,
                abs(mean_mouse_time) <= 0.1) %>% 
                  arrange(-abs(cov)) %>% 
                  slice_head(n = 10)) +
   theme_vaxgo() +
  labs(title = "Which genes vary only in human?",
       subtitle = "Top 10 genes with highest covariance. Mean cutoff > 0.1.")

genes_vary_mouse = cov_genes_FIT_training %>% 
  ggplot() +
  aes(x = mean_human_time,
      y = mean_mouse_time) +
    geom_point(color = "#90A4AEFF", fill = NA, pch = 21) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  scale_y_continuous(limits = c(-1.5, 1.5)) +
  gghighlight(abs(mean_mouse_time) >= 0.1,
                abs(mean_human_time) <= 0.1,
              use_direct_label = FALSE,
              unhighlighted_params = list(alpha = 0.2, fill = NA)) +
  geom_label_repel(aes(label = human_symbol), max.overlaps = 20, force_pull = 4, size = 3,
                  data = cov_genes_FIT_training %>% 
                    filter(abs(mean_mouse_time) >= 0.1,
                abs(mean_human_time) <= 0.1) %>% 
                  arrange(-abs(cov)) %>% 
                  slice_head(n = 10)) +

  theme_vaxgo() +
  labs(title = "Which genes vary only in mouse?",
       subtitle = "Top 10 genes with highest covariance. Mean cutoff > 0.1") 


genes_vary_mouse_human = cov_genes_FIT_training %>% 
  ggplot() +
  aes(x = mean_human_time,
      y = mean_mouse_time) +
  geom_point(color = "black", fill = NA, pch = 21) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  scale_y_continuous(limits = c(-1.5, 1.5)) +
  gghighlight(abs(mean_human_time) >= 0.1,
                abs(mean_mouse_time) >= 0.1,
                            unhighlighted_params = list(alpha = 0.2, fill = NA)) +
  geom_label_repel(aes(label = human_symbol), max.overlaps = 20, force_pull = 4, size = 3,
                  data = cov_genes_FIT_training %>% 
                    filter(abs(mean_human_time) >= 0.1,
                abs(mean_mouse_time) >= 0.1) %>% 
                  arrange(-abs(cov)) %>% 
                  slice_head(n = 10)) +
  theme_vaxgo() +
  labs(title = "Which genes vary in both human and mouse?",
       subtitle = "Top 10 genes with highest covariance. Mean cutoff > 0.1")

genes_notvary_mouse_human = cov_genes_FIT_training %>% 
  ggplot() +
  aes(x = mean_human_time,
      y = mean_mouse_time) +
  geom_point(color = "black", fill = NA, pch = 21) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  scale_y_continuous(limits = c(-1.5, 1.5)) +
  gghighlight(abs(mean_human_time) <= 0.1,
                abs(mean_mouse_time) <= 0.1,
              unhighlighted_params = list(alpha = 0.2, fill = NA)) +
  geom_label_repel(aes(label = human_symbol), 
                  # color = "red",
                  max.overlaps = 20, force_pull = 4, size = 3, 
                  data = cov_genes_FIT_training %>% 
                    filter(abs(mean_human_time) <= 0.1, 
                             abs(mean_mouse_time) <= 0.1) %>%  
                    arrange(-abs(cov)) %>% 
                    slice_head(n = 10)) +
  theme_vaxgo() +
  labs(title = "Which genes do not vary in both human and mouse?",
       subtitle = "Top 10 genes with highest covariance. Mean cutoff < 0.1")
  

#Plot all
genes_vary_mouse + genes_vary_human + genes_vary_mouse_human + genes_notvary_mouse_human +
  plot_layout(guides = "collect", axes = "collect", axis_titles =  "collect",
              ncol =  2)
  
```







#### Enrichment analysis

```{r fig.width=10, fig.height= 8}
organism = "org.Hs.eg.db"

library(msigdbr)
library(fgsea)

#All Gene ontologies
genes_vary_human_all_cov_FIT = cov_genes_FIT_training %>% 
  select(genes = human_symbol, value = cov) %>% 
  mutate(condition = "Vary in human, mean > 0.1") %>% 
  bind_rows(genes_vary_mouse_all_FIT %>% 
            select(genes = human_symbol, value = cov) %>% 
              mutate(condition = "Vary in Mouse, mean > 0.1"),
            genes_vary_human_mouse_all_FIT %>% 
            select(genes = human_symbol, value = cov) %>% 
              mutate(condition = "Vary in Mouse and Human, mean > 0.1"),
            genes_not_vary_human_mouse_all_FIT %>% 
            select(genes = human_symbol, value = cov) %>% 
              mutate(condition = "No variation in Mouse and Human, mean < 0.1"),
            cov_genes_FIT_training %>%
              select(genes = human_symbol, value = cov) %>%
              mutate(condition = "All genes, no cutoff, only covariance"))


#GSEA for GOs
gseGO_all_cov_FIT = gseGO_all(genes_vary_human_all_cov_FIT)

#GSEA for hallmarks
#Retrieve human H (hallmark) gene set
msigdbr_df <- msigdbr(species = "human", category = "H") %>% 
  select(process = gs_name, genes = human_gene_symbol) %>% 
  mutate(process = str_remove(process, "HALLMARK_"))

gsea_hallmarks_all_cov_FIT= autoGSEA(df = genes_vary_human_all_cov_FIT %>% 
                                       rename(log2fold_change = value),
         TERM2GENE = msigdbr_df,
         geneset_name = "Hallmarks MSigDB") %>% 
  clean_names()
```


```{r fig.width=10, fig.height= 8}
#ORA Gene ontologies
oraGO_all_cov_vary_both_FIT <- enrichGO(gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "Vary in Mouse and Human, mean > 0.1") %>% 
                                      pull(genes),
                                   OrgDb = org.Hs.eg.db,
                                   keyType = 'SYMBOL',
                                   readable = T,
                                   ont = "BP",
                                   pAdjustMethod = "BH",
                                   qvalueCutoff = 0.50) %>% 
  as_data_frame() %>%
  clean_names() %>%
  mutate(log_q = -log10(qvalue),
         condition = "Vary in Mouse and Human, mean > 0.1") %>%
  arrange(-log_q)

oraGO_all_cov_vary_human_FIT <- enrichGO(gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "Vary in human, mean > 0.1") %>% 
                                      pull(genes),
                                   OrgDb = org.Hs.eg.db,
                                   keyType = 'SYMBOL',
                                   readable = T,
                                   ont = "BP",
                                   pAdjustMethod = "BH",
                                   qvalueCutoff = 0.50) %>% 
  as_data_frame() %>%
  clean_names() %>%
  mutate(log_q = -log10(qvalue),
         condition = "Vary in human, mean > 0.1") %>%
  arrange(-log_q)

oraGO_all_cov_vary_mouse_FIT <- enrichGO(gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "Vary in Mouse, mean > 0.1") %>% 
                                      pull(genes),
                                   OrgDb = org.Hs.eg.db,
                                   keyType = 'SYMBOL',
                                   readable = T,
                                   ont = "BP",
                                   pAdjustMethod = "BH",
                                   qvalueCutoff = 0.50) %>% 
  as_data_frame() %>%
  clean_names() %>%
  mutate(log_q = -log10(qvalue),
         condition = "Vary in mouse, mean > 0.1") %>%
  arrange(-log_q)

oraGO_all_cov_notvary_human_mouse_FIT <- enrichGO(gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "No variation in Mouse and Human, mean < 0.1") %>% 
                                      pull(genes),
                                   OrgDb = org.Hs.eg.db,
                                   keyType = 'SYMBOL',
                                   readable = T,
                                   ont = "BP",
                                   pAdjustMethod = "BH",
                                   qvalueCutoff = 0.50) %>% 
  as_data_frame() %>%
  clean_names() %>%
  mutate(log_q = -log10(qvalue),
         condition = "No variation in Mouse and Human, mean < 0.1") %>%
  arrange(-log_q)



oraGO_all_cov_all_conditions_FIT = bind_rows(oraGO_all_cov_vary_both_FIT, 
          oraGO_all_cov_vary_human_FIT, 
          oraGO_all_cov_vary_mouse_FIT,
          oraGO_all_cov_notvary_human_mouse_FIT)



#ORA Hallmarks

ora_hallmakrs_vary_both_FIT <- enricher(
  gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "Vary in Mouse and Human, mean > 0.1") %>% 
                                      pull(genes), # A vector of your genes of interest
  pvalueCutoff = 0.50, # Can choose a FDR cutoff
  pAdjustMethod = "BH", # Method to be used for multiple testing correction
  TERM2GENE = msigdbr_df) %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  mutate(condition = "Vary in Mouse and Human, mean > 0.1")

ora_hallmakrs_vary_human_FIT <- enricher(
  gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "Vary in human, mean > 0.1") %>% 
                                      pull(genes), # A vector of your genes of interest
  pvalueCutoff = 0.50, # Can choose a FDR cutoff
  pAdjustMethod = "BH", # Method to be used for multiple testing correction
  TERM2GENE = msigdbr_df) %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  mutate(condition = "Vary in human, mean > 0.1")

ora_hallmakrs_vary_mouse_FIT <- enricher(
  gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "Vary in Mouse, mean > 0.1") %>% 
                                      pull(genes), # A vector of your genes of interest
  pvalueCutoff = 0.50, # Can choose a FDR cutoff
  pAdjustMethod = "BH", # Method to be used for multiple testing correction
  TERM2GENE = msigdbr_df) %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  mutate(condition = "Vary in Mouse, mean > 0.1")

ora_hallmakrs_no_variation_FIT <- enricher(
  gene = genes_vary_human_all_cov_FIT %>% 
                                      filter(condition == "No variation in Mouse and Human, mean < 0.1") %>% 
                                      pull(genes), # A vector of your genes of interest
  pvalueCutoff = 0.50, # Can choose a FDR cutoff
  pAdjustMethod = "BH", # Method to be used for multiple testing correction
  TERM2GENE = msigdbr_df) %>% 
  as.data.frame() %>% 
  clean_names() %>% 
  mutate(condition = "No variation in Mouse and Human, mean < 0.1")


ora_hallmarks_all_cov_all_conditions_FIT = bind_rows(ora_hallmakrs_vary_both_FIT, 
          ora_hallmakrs_vary_human_FIT, 
          ora_hallmakrs_vary_mouse_FIT,
          ora_hallmakrs_no_variation_FIT) %>% 
  mutate(log_q = -log(qvalue))


```


ORA GOs
```{r fig.height=8, fig.width=8}
row_clustered = oraGO_all_cov_all_conditions %>% 
    dplyr::select(condition, description, log_q) %>% 
    distinct() %>% 
    pivot_wider(names_from = "condition",
                values_from= "log_q") %>%
    column_to_rownames("description") %>% 
    as.matrix() %>% 
    replace(is.na(.), 0) %>% 
    dist(.) %>% 
    hclust()


oraGO_all_cov_all_conditions %>% 
  clean_names() %>% 
  # filter(p_adjust < 0.01) %>% 
  filter(description %in% c(row_clustered$labels)) %>% 
  group_by(condition) %>% 
  arrange(p_adjust) %>% 
  slice_head(n = 10) %>% 
  select(condition, description, log_q, p_adjust, everything()) %>% 
    mutate(signific = case_when(p_adjust <= 0.10 ~ "*",
                              p_adjust <= 0.25 ~ "-",
                              p_adjust <= 0.50 ~ "/",
                              p_adjust <= 0.05 ~ "**",
                              TRUE ~ "")) %>% 
  mutate(condition = fct_relevel(condition, "Vary in mouse, mean > 0.1", 
                                 "Vary in human, mean > 0.1", 
                                 "Vary in Mouse and Human, mean > 0.1"
                                 )) %>% 
  ggplot(aes(x=fct_rev(condition), y = description, fill = log_q)) +
  geom_point(aes(size = count),
             pch = 21) +
  geom_text(aes(label = signific), size = 4, vjust = 0.5, color = "black") +
  scale_fill_gradient(low = "white", high = "red") +
  scale_x_discrete(labels = label_wrap(20)) +
    theme_minimal() + 
    theme(axis.text = element_text(color = "black", size = 8) ,
          axis.line  = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1),
          axis.ticks = element_blank(),
          # panel.grid = element_blank(), 
          plot.margin = margin(1, 1, 2, 2, unit = "cm"),
          legend.direction = "vertical",
          legend.position = "left") +
    labs(x = "",
         y = "",
         title = "Top 5 enriched genes, ORA") +
    scale_y_discrete(position = "right") 

```


ORA Hallmarks
```{r fig.height=8, fig.width=8}
row_clustered = ora_hallmarks_all_cov_all_conditions_FIT %>% 
    dplyr::select(condition, description, log_q) %>% 
    distinct() %>% 
    pivot_wider(names_from = "condition",
                values_from= "log_q") %>%
    column_to_rownames("description") %>% 
    as.matrix() %>% 
    replace(is.na(.), 0) %>% 
    dist(.) %>% 
    hclust()


ora_hallmarks_all_cov_all_conditions_FIT %>% 
  clean_names() %>% 
  # filter(p_adjust < 0.01) %>% 
  filter(description %in% c(row_clustered$labels)) %>% 
  group_by(condition) %>% 
  arrange(p_adjust) %>% 
  # slice_head(n = 10) %>% 
  select(condition, description, log_q, p_adjust, everything()) %>% 
    mutate(signific = case_when(p_adjust <= 0.10 ~ "*",
                              p_adjust <= 0.25 ~ "-",
                              p_adjust <= 0.50 ~ "/",
                              p_adjust <= 0.05 ~ "**",
                              TRUE ~ "")) %>% 
  mutate(condition = fct_relevel(condition, "Vary in mouse, mean > 0.1", 
                                 "Vary in human, mean > 0.1", 
                                 "Vary in Mouse and Human, mean > 0.1"
                                 )) %>% 
  ggplot(aes(x=fct_rev(condition), y = description, fill = log_q)) +
  geom_tile(color = "white",
            size = 0, na.rm = F) + 
  geom_text(aes(label = signific), size = 6, vjust = 0.8, color = "black") +
  scale_fill_gradient(low = "white", high = "red") +
  scale_x_discrete(labels = label_wrap(20)) +
    theme_minimal() + 
    theme(axis.text = element_text(color = "black", size = 8) ,
          axis.line  = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.text.y = element_text(angle = 0, vjust = 0.5, hjust=1),
          axis.ticks = element_blank(),
          # panel.grid = element_blank(), 
          plot.margin = margin(1, 1, 2, 2, unit = "cm"),
          legend.direction = "vertical",
          legend.position = "left") +
    labs(x = "",
         y = "",
         title = "ORA, MSigDB Hallmarks, FIT training") +
    scale_y_discrete(position = "right") 

```

GSEA Gene ontologies

```{r fig.height=8, fig.width=8}
row_clustered = gseGO_all_cov %>% 
    dplyr::select(condition, description, nes) %>% 
    # filter(condition == "All genes, no cutoff, only covariance") %>% 
    distinct() %>% 
    pivot_wider(names_from = "condition",
                values_from= "nes") %>%
    column_to_rownames("description") %>% 
    as.matrix() %>% 
    replace(is.na(.), 0) %>% 
    dist(.) %>% 
    hclust()


gseGO_all_cov %>% 
  clean_names() %>% 
  # filter(p_adjust < 0.01) %>% 
  filter(description %in% c(row_clustered$labels)) %>% 
  group_by(condition) %>% 
  arrange(p_adjust) %>% 
  slice_head(n = 5) %>% 
  select(condition, description, nes, p_adjust, everything()) %>% 
    mutate(signific = case_when(p_adjust <= 0.10 ~ "*",
                              p_adjust <= 0.25 ~ "-",
                              p_adjust <= 0.50 ~ "/",
                              p_adjust <= 0.05 ~ "**",
                              TRUE ~ "")) %>% 
  ggplot(aes(x=condition, y = description, fill = nes)) +
  geom_tile(color = "white",
            size = 0, na.rm = F) + 
  geom_text(aes(label = signific), size = 4, vjust = 0.5, color = "black") +
  scale_y_discrete(labels = label_wrap(15)) +
    theme_minimal() + 
    theme(axis.text = element_text(color = "black", size = 8) ,
          axis.line  = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.text.y = element_text(angle = 0, vjust = 1, hjust=1),
          axis.ticks = element_blank(),
          panel.grid = element_blank(), 
          plot.margin = margin(1, 1, 1, 4, unit = "cm"),
          legend.direction = "horizontal",
          legend.position = "top") +
    labs(x = "",
         y = "",
         title = "Top 5 enriched genes, GSEA, by covariance") +
    scale_fill_gradient2(
        low = "#4DBBD5FF",      # azul para -1
        mid = "white",          # branco para 0
        high = "#DC0000FF",     # vermelho para +1
        midpoint = 0, 
        n.breaks = 3,
        oob = scales::squish,
        limits = c(-1, 1),      # fixa o intervalo
        name = "NES") +
    scale_y_discrete(position = "right") 

```


GSEA Hallmarks

```{r fig.height=10, fig.width=10}
gsea_hallmarks_all_cov$gsea



row_clustered = gsea_hallmarks_all_cov$gsea %>% 
  clean_names() %>% 
    dplyr::select(condition, description, nes) %>% 
    # filter(condition == "All genes, no cutoff, only covariance") %>% 
    distinct() %>% 
    pivot_wider(names_from = "condition",
                values_from= "nes") %>%
    column_to_rownames("description") %>% 
    as.matrix() %>% 
    replace(is.na(.), 0) %>% 
    dist(.) %>% 
    hclust()


gsea_hallmarks_all_cov$gsea %>% 
  clean_names() %>% 
  # filter(p_adjust < 0.01) %>% 
  filter(description %in% c(row_clustered$labels)) %>% 
  group_by(condition) %>% 
  arrange(p_adjust) %>% 
  # slice_head(n = 5) %>% 
  select(condition, description, nes, p_adjust, everything()) %>% 
    mutate(signific = case_when(p_adjust <= 0.10 ~ "*",
                              p_adjust <= 0.25 ~ "-",
                              p_adjust <= 0.50 ~ "/",
                              p_adjust <= 0.05 ~ "**",
                              TRUE ~ "")) %>% 
  ggplot(aes(x=condition, y = description, fill = nes)) +
  geom_tile(color = "white",
            size = 0, na.rm = F) + 
  geom_text(aes(label = signific), size = 4, vjust = 0.5, color = "black") +
  scale_y_discrete(labels = label_wrap(15)) +
    theme_minimal() + 
    theme(axis.text = element_text(color = "black", size = 8) ,
          axis.line  = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
          axis.text.y = element_text(angle = 0, vjust = 1, hjust=1),
          axis.ticks = element_blank(),
          panel.grid = element_blank(), 
          plot.margin = margin(1, 1, 1, 4, unit = "cm"),
          legend.direction = "horizontal",
          legend.position = "top") +
    labs(x = "",
         y = "",
         title = "Top 5 enriched genes, GSEA, by covariance") +
    scale_fill_gradient2(
        low = "#4DBBD5FF",      # azul para -1
        mid = "white",          # branco para 0
        high = "#DC0000FF",     # vermelho para +1
        midpoint = 0, 
        n.breaks = 3,
        oob = scales::squish,
        limits = c(-1, 1),      # fixa o intervalo
        name = "NES") +
    scale_y_discrete(position = "right") 
```












