---
title: "Summary_Analyses"
output: html_document
---


#ROC curve
```{r}
#Fluad vaccination
#Use Fluad uniform and human perfect distributions as reference to make the visualization easier
roc_curve_data_Fluad_Immune = readRDS(here("tables", "roc_curve_data_Fluad_Immune.rds")) %>% 
  filter(model %in% c("Mouse", "Uniform", "Human")) %>% 
  mutate(condition = case_when(model == "Uniform" ~ "Uniform",
                               model == "Human" ~ "Human",
                               T ~ condition)) %>% 
  filter(timepoint == 1)

roc_curve_data_Fluad_AllGenes = readRDS(here("tables", "roc_curve_data_Fluad_AllGenes.rds")) %>% 
  filter(model %in% c("Mouse", "Uniform", "Human")) %>% 
  mutate(condition = case_when(model == "Uniform" ~ "Uniform",
                               model == "Human" ~ "Human",
                               T ~ condition)) %>% 
  filter(timepoint == 1)

#Engerix B vaccination
roc_curve_data_EngerixB_AllGenes = readRDS(here("tables", "roc_curve_data_EngerixB_AllGenes.rds")) %>% 
  filter(model == "Mouse") %>% 
  filter(timepoint == 7)
roc_curve_data_EngerixB_Immune = readRDS(here("tables", "roc_curve_data_EngerixB_Immune.rds")) %>% 
  filter(model == "Mouse") %>% 
  filter(timepoint == 7)

#E. coli infection
roc_curve_data_EcoliInfection_Mouse24h_HumanHospitalization_Immune <- readRDS(here("tables", "roc_curve_data_EcoliInfection_Mouse24h_HumanHospitalization_Immune.rds")) %>% 
  filter(model == "Mouse")
roc_curve_data_EcoliInfection_Mouse24h_HumanHospitalization_AllGenes <- readRDS(here("tables", "roc_curve_data_EcoliInfection_Mouse24h_HumanHospitalization_AllGenes.rds")) %>% 
  filter(model == "Mouse")

#S. aureus
roc_curve_data_Saureus_Infection_AllGenes <- readRDS(here("tables", "roc_curve_data_Saureus_Infection_AllGenes.rds")) %>% 
  filter(model == "Mouse")
roc_curve_data_Saureus_Infection_Immune <- readRDS(here("tables", "roc_curve_data_Saureus_Infection_Immune.rds")) %>% 
  filter(model == "Mouse")


#Combine roc curves
roc_curves_combined = bind_rows(roc_curve_data_Fluad_Immune,
                                roc_curve_data_Fluad_AllGenes,
                                roc_curve_data_EngerixB_AllGenes,
                                roc_curve_data_EngerixB_Immune,
                                roc_curve_data_EcoliInfection_Mouse24h_HumanHospitalization_Immune,
                                roc_curve_data_EcoliInfection_Mouse24h_HumanHospitalization_AllGenes,
                                roc_curve_data_Saureus_Infection_AllGenes,
                                roc_curve_data_Saureus_Infection_Immune) %>% 
  mutate(geneset = if_else(str_detect(filename, "Immune"), "Immune", "All"),
         group = if_else(str_detect(condition, "Vaccination"), "Vaccination", "Infection"),
         condition = str_remove(condition, " infection|vaccination|_Vaccination"),
         condition = fct_relevel(condition, "Human", "Uniform", "Fluad", "E. coli", "S. aureus")) 

roc_curves_combined 
roc_curves_combined %>% 
  dplyr::count(condition)
```


```{r fig.height=4, fig.width=5}
##### PLOT ROC Curve ------

filename = "Vaccinations_Infections"
filename_title ="Vaccinations_Infections"

roc_curve_plot = roc_curves_combined %>% 
  ggplot(aes(x = 1 - specificity, 
             y = sensitivity, 
             color = condition)) +
  geom_path(linewidth = 1,
            alpha = 1) +
  geom_abline(lty = 3) +
  theme_vaxgo() +
  facet_grid(~fct_rev(comparison)~geneset) + 
  scale_color_manual(values = c(
    "Fluad " = "#4DBBD5FF",
    "EngerixB" = "#0466c8",
    "E. coli"   = "#c55df6",
    "S. aureus" = "#9381ff",
    "Human" = "#90A4AEFF",
    "Uniform" = "gray80"
    )) +
  labs(
    title = "Vaccinations and infections, Mouse as model", 
  x = "FPR",
  y = "TPR",
  color = "Model") + 
  theme(legend.position = "right",
    strip.text = element_text(size = 10),
    strip.placement = "outside",
    strip.text.y = element_text(size = 10,),
    axis.text.x = element_text(size = 10, angle = 0, hjust = 0.5, vjust = 0.5),
    axis.text.y = element_text(size = 10),
    panel.spacing.x = unit(0.5, "lines"),
    legend.key = element_blank()
  ) +
  scale_x_continuous(n.breaks = 3) +
  scale_y_continuous(n.break = 3)


roc_curve_plot

#Save
roc_curve_plot %>%
  ggsave(filename = here("Figures", paste0("roc_curve_plot_", filename, ".png")),
         width = 5,
         height = 4)

```

