```{r}
pairwise_human_fit_test =  read_rds(here("FIT_Mouse2man", "pairwise_human_fit_test.rds"))
```


```{r fig.height=4, fig.width=8}

quantile_diff_genes = pairwise_human_fit_test 

abs_diff_correlation_plot_data_split_qn = quantile_diff_genes %>% 
  mutate(
    quartile_label = cut(abs(human_2_mouse_qn),
                         breaks = quantile(abs(human_2_mouse_qn),
                                           probs = c(0, 0.10, 0.25, 0.5, 0.75, 1),
                                           na.rm = TRUE),
                         include.lowest = TRUE,
                         labels = c("Q10", "Q25", "Q50", "Q75", "Q100")),
    timepoint_day = paste0("Day ", timepoint)) %>% 
  mutate(pval_mouse_adj = if_else(pval_mouse_adj <= 0.05, "DEG", "Not DEG"),
         pval_human_adj = if_else(pval_human_adj <= 0.05, "DEG", "Not DEG"))

abs_diff_correlation_plot_data_split_qn %>% dplyr::count(timepoint)

#Get all genes
quantiles <- quantile(abs(quantile_diff_genes$human_2_mouse_qn), 
                    probs = c(0.10, 0.25, 0.5, 0.75, 1), 
                    na.rm = TRUE)

diff_correlation_plot_data_qn = quantile_diff_genes %>% 
  arrange(timepoint)  %>% 
  ungroup() %>% 
  #Split by quantile
    mutate(
    Q10 = abs(human_2_mouse_qn) <= quantiles[1],
    Q25 = abs(human_2_mouse_qn) <= quantiles[2],
    Q50 = abs(human_2_mouse_qn) <= quantiles[3],
    Q75 = abs(human_2_mouse_qn) <= quantiles[4],
    Q100 = abs(human_2_mouse_qn) <= quantiles[5]
  ) %>%
  #Cumulative
  pivot_longer(cols = starts_with("Q"),
               names_to = "quartile_label",
               values_to = "in_quantile") %>%
  mutate(quartile_label = fct_relevel(quartile_label, "Q10", "Q25", "Q50", "Q75", "Q100")) %>% 
  filter(in_quantile) %>%
  select(-in_quantile)
```


```{r fig.height=4, fig.width=8}
abs_diff_correlation_plot_data_split_qn %>% 
  ungroup() %>% 
  ggplot() +
  aes(x = mean_mouse_qn,
      y = mean_human_qn) +
  facet_wrap(~paste("Day", timepoint)) +
  #All points, colored by differences
  geom_point(
             aes(color = quartile_label,
                 # alpha = quartile_label,
                 fill = quartile_label),
             # fill = NA,
             # alpha = 1,
             pch = 21) +

  #Same DEGs (WORST)
  geom_point(color = "#4DBBD5FF",
             fill = "#4DBBD5FF",
             alpha = 1,
             size = 0.5,
             pch = 21,
             data = abs_diff_correlation_plot_data_split_qn %>%
               filter(pval_mouse_adj == pval_human_adj,
                      pval_mouse_adj == "DEG") %>%
               filter(quartile_label %in% c("Q50", "Q75", "Q100"))) +
  #Same DEGs (BEST)
  geom_point(color = "black",
             fill = "#4DBBD5FF",
             alpha = 1,
             size = 2,
             pch = 21,
             data = abs_diff_correlation_plot_data_split_qn %>%
               filter(pval_mouse_adj == pval_human_adj,
                      pval_mouse_adj == "DEG") %>%
               filter(quartile_label %in% c(
                 "Q10",
                 "Q25"
                 ))) +
   #Guide lines
  geom_abline(alpha = 0.2, linetype = 2) +
  geom_abline(slope = -1, alpha = 0.2, linetype = 2) +
  geom_hline(yintercept = 0, alpha = 1, linetype = 2) +
  geom_vline(xintercept = 0, alpha = 1, linetype = 2) +
  
  scale_color_manual(values = c("Q10" = "black",
                               "Q25" = "gray25",
                               "Q50" = "gray50",
                               "Q75" = "gray75",
                               "Q100" = "gray90")) +
  scale_fill_manual(values = c("Q10" = "black",
                               "Q25" = "gray25",
                               "Q50" = "gray50",
                               "Q75" = "gray75",
                               "Q100" = "gray90")) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  scale_y_continuous(limits = c(-1.5, 1.5)) +
  
  theme_vaxgo() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.position = "right",
        legend.direction = "vertical",
        legend.key.width = unit(0.4, 'cm'),
        legend.key.height = unit(0.4, 'cm'),
        legend.key = element_blank(),
        legend.title = element_text(size = 10, vjust = 0.9),
        legend.text = element_text(size = 7, vjust = 0.5, hjust = -0.2)) +
  labs(title = "Which genes and DEGs vary in both human and mouse?",
       subtitle = "Differences in mouse to human, by timepoint.In colors, DEGs in human AND mouse, p_adjust < 0.05, |diff| < 0.2. \nPurple = Negatively correlated, Blue = Positively correlated",
       x = "Mouse L2FC",
       y = "Human L2FC",
       alpha = "Quantiles",
       fill = "Quantiles",
       color = "|Z|")


```






### plot btms with CIs

Engerix
```{r fig.height=4, fig.width=8}

dge_btm_mean_process_samples = 
  readRDS(file = here("tables", "engerixb_dge_btm_mean_process_samples.rds"))


dge_btm_mean_process = dge_btm_mean_process_samples %>% 
  group_by(organism, timepoint, process) %>% 
  summarize(
    mean = mean(log2fc, na.rm = TRUE) %>% round(2),
    median = median(log2fc, na.rm = TRUE) %>% round(2),
    min = min(log2fc, na.rm = TRUE) %>% round(2),
    max = max(log2fc, na.rm = TRUE) %>% round(2),
    sd = sd(log2fc, na.rm = T),
    n = sum(!is.na(log2fc)),
    se = sd/sqrt(n),
    t_critical = qt(0.975, df = n - 1),
    ci_lower = mean - t_critical * se,
    ci_upper = mean + t_critical * se,
    p_value = t.test(log2fc, mu = 0)$p.value,
    .groups = "drop",
    group,
    subgroup
  ) %>%
  distinct() %>% 
  mutate(p_adj = p.adjust(p_value, method = "BH"), 
         sig_cat = case_when(p_adj < 0.01 ~ "< 0.01", 
                             p_adj < 0.05 ~ "< 0.05",
                             p_adj < 0.10 ~ "< 0.10", 
                             p_adj < 0.25 ~ "< 0.25", 
                             TRUE ~ "≥ 0.25"),
         sig_cat = factor(sig_cat,
                   levels = c("< 0.01", "< 0.05", "< 0.10", "< 0.25", "≥ 0.25"))) %>% 
  select(organism, timepoint, process, mean, median, p_adj, p_value, sig_cat, ci_lower, ci_upper, group, subgroup) %>% 
  pivot_wider(names_from = organism, 
              values_from = c(mean, median, p_value, p_adj, ci_lower, ci_upper, sig_cat), 
              names_sep = "_", names_sort = TRUE) 



dge_btm_mean_process  %>% 
  ggplot() +
  aes(x = mean_Mouse,
      y = mean_Human) +
  facet_wrap(~timepoint, scales = "free") +
  geom_point(aes(fill = group), alpha = 1, size = 3, 
             color = "black", pch = 21,
             data = . %>% filter(p_value_Mouse <= 0.25| p_value_Mouse <= 0.25)) +
  geom_point(aes(fill = group), alpha = 0.2, size = 3, 
             color = "black", pch = 21,
             data = . %>% filter(p_value_Mouse > 0.25| p_value_Mouse > 0.25)) +
  geom_hline(yintercept = 0, alpha = 0.2, linetype = 2) +
  geom_vline(xintercept = 0, alpha = 0.2, linetype = 2) +
  theme_vaxgo() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        strip.text.x = element_text(size = 10),
        strip.text.y = element_blank(),
        legend.position = "none") +
  scale_color_manual(values = immune_colors) +
  scale_fill_manual(values = immune_colors) +
  labs(x = "Mouse Log2FC", 
       y = "Human Log2FC", 
       color = "",
       fill = "",
       title = "Mouse vs. Human, BTMs,\nEngerixB vaccination")

```





```{r}
#Import
dge_btm_mean_process_samples = 
  readRDS(file = here("tables", "dge_Ecoli_btm_mean_process_samples.rds")) %>% 
  mutate(timepoint = if_else(is.na(timepoint), "24", timepoint)) %>% 
  filter(timepoint == 24)


dge_btm_mean_process = dge_btm_mean_process_samples %>% 
  group_by(organism, timepoint, process) %>% 
  summarize(
    mean = mean(log2fc, na.rm = TRUE) %>% round(2),
    median = median(log2fc, na.rm = TRUE) %>% round(2),
    min = min(log2fc, na.rm = TRUE) %>% round(2),
    max = max(log2fc, na.rm = TRUE) %>% round(2),
    sd = sd(log2fc, na.rm = T),
    n = sum(!is.na(log2fc)),
    se = sd/sqrt(n),
    t_critical = qt(0.975, df = n - 1),
    ci_lower = mean - t_critical * se,
    ci_upper = mean + t_critical * se,
    p_value = t.test(log2fc, mu = 0)$p.value,
    .groups = "drop",
    group,
    subgroup
  ) %>%
  distinct() %>% 
  mutate(p_adj = p.adjust(p_value, method = "BH"), 
         sig_cat = case_when(p_adj < 0.01 ~ "< 0.01", 
                             p_adj < 0.05 ~ "< 0.05",
                             p_adj < 0.10 ~ "< 0.10", 
                             p_adj < 0.25 ~ "< 0.25", 
                             TRUE ~ "≥ 0.25"),
         sig_cat = factor(sig_cat,
                   levels = c("< 0.01", "< 0.05", "< 0.10", "< 0.25", "≥ 0.25"))) %>% 
  select(organism, timepoint, process, mean, median, p_adj, p_value, sig_cat, ci_lower, ci_upper, group, subgroup) %>% 
  pivot_wider(names_from = organism, 
              values_from = c(mean, median, p_value, p_adj, ci_lower, ci_upper, sig_cat), 
              names_sep = "_", names_sort = TRUE) 



dge_btm_mean_process %>%
  mutate(
    significance = case_when(
      p_adj_Mouse <= 0.25 & p_adj_Human <= 0.25 ~ "Significant in both",
      p_adj_Mouse > 0.25 & p_adj_Human > 0.25 ~ "Non-significant in both",
      TRUE ~ "Mixed"
    ),
    significance = factor(
      significance,
      levels = c("Significant in both", "Mixed", "Non-significant in both")
    )
  ) %>%
  ggplot(aes(x = mean_Mouse, y = mean_Human)) +
  facet_wrap(~timepoint, scales = "free") +
  
  geom_point(
  aes(fill = group, color = group, shape = significance),
  size = 3,
  stroke = 0.7) +
scale_fill_manual(values = immune_colors, name = "Group") +
scale_color_manual(values = immune_colors, guide = "none") + # esconde legenda duplicada
  
  geom_hline(yintercept = 0, alpha = 0.2, linetype = 2) +
  geom_vline(xintercept = 0, alpha = 0.2, linetype = 2) +
  
  theme_vaxgo() +
  theme(
    axis.text.x = element_text(size = 10),
    axis.text.y = element_text(size = 10),
    strip.text.x = element_text(size = 10),
    strip.text.y = element_blank()
  ) +
  
#   scale_fill_manual(values = immune_colors, name = "Group") +
#   guides(
#   fill = guide_legend(override.aes = list(color = "black"))
# ) +
  scale_shape_manual(
    values = c(
      "Significant in both" = 21,  # círculo cheio
      "Mixed" = 24,                # triângulo
      "Non-significant in both" = 22  # quadrado
    ),
    name = "Adjusted p-value match"
  ) +
  
  labs(
    x = "Mouse Log2FC",
    y = "Human Log2FC",
    title = "Mouse vs. Human, BTMs,\nEngerixB vaccination"
  )
```



#Scatterplot of correlation (arrows, day)
```{r fig.height=3, fig.width=10}

zscore_genes_plot_timepoints = zscore_genes %>% 
  mutate(timepoint = as.character(timepoint)) %>% 
  ggplot() +
  aes(x = mean_human,
      y = mean_mouse) +
  #All points, colored by zscore
  geom_point(color ="gray90",
             fill = NA,
             pch = 21,
             alpha = 0.4) +
  #Select
  geom_point(aes(shape = as.character(timepoint)),
             # pch = 21, 
             alpha = 0.5,
             # stroke = 0.5, 
             size = 2, 
             color = "#4DBBD5FF",
            data =degs_pos_neg_mouse %>% 
              filter(quantile_label %in% c("Q10", "Q25", "Q50"))) +
  geom_path(aes(group = human_symbol),
            arrow=arrow(length=unit(0.05,"in")), 
            show.legend= FALSE,
            alpha = 0.5,
            data = degs_pos_neg_mouse %>% 
              filter(quantile_label %in% c("Q10", "Q25", "Q50")),
            # color = "black"
            ) +
  # scale_color_manual(values = c("1" = "#4DBBD5",
  #                               "3" = "#A6DDEA",
  #                               "7" = "white")) +
    scale_x_continuous(limits = c(-0.6, 0.6)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) +
  geom_abline(alpha = 0.5, linetype = 2) +
  geom_abline(slope = -1, alpha = 0.5, linetype = 2) +
  facet_wrap(~quantile_label) + 
  theme_vaxgo() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
         legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.key = element_rect(colour = NA)) +
  labs(title = "Are these genes well predicted in most timepoints?",
       subtitle = "Differences in mouse to human, using DEGs in human AND mouse, p_adjust < 0.05.\nAll timepoints. Only Q50 genes.",
       x = "Human L2FC",
       y = "Mouse L2FC",
       fill = "Timepoint",
       color = "Timepoint",
       shape = "Timepoint")  

zscore_genes_plot_timepoints$layers[[2]]

```



```{r}

degs_segments <- degs_pos_neg_mouse %>%
  filter(quantile_label %in% c("Q25")) %>%
  mutate(quantile_label = if_else(quantile_label == "Q25", "<Q25", quantile_label)) %>% 
  bind_rows(degs_pos_neg_mouse_split %>% 
    mutate(quantile_label = if_else(quartiles_diff == "Q100" | 
                                      quartiles_diff == "Q75", "Q75>", 
                                    quartiles_diff)) %>% 
      filter(quantile_label == "Q75>")) %>% 
  arrange(human_symbol, timepoint) %>%
  group_by(human_symbol, quantile_label) %>%
  mutate(
    mean_human_next = lead(mean_human),
    mean_mouse_next = lead(mean_mouse),
    timepoint_next = lead(timepoint),
    direction = paste0("D", timepoint, "→D", timepoint_next)
  ) %>%
  filter(!is.na(mean_human_next), !is.na(mean_mouse_next)) %>%
  ungroup() %>% 
  filter(!(mean_human == mean_human_next & mean_mouse == mean_mouse_next))
  
  

degs_segments
```


```{r}
# Plot com caminhos coloridos por direção
zscore_genes_plot_timepoints <- zscore_genes %>% 
  mutate(timepoint = as.character(timepoint)) %>% 
  ggplot() +
  aes(x = mean_human, y = mean_mouse) +
  # Curva com seta no fim
  geom_curve(data = degs_segments,
             aes(x = mean_human, y = mean_mouse,
                 xend = mean_human_next, yend = mean_mouse_next,
                 color = direction,
                 group = human_symbol),
             curvature = 0,     # Ajuste a curvatura conforme desejado
             size = 1,
             arrow = arrow(length = unit(0.1, "in")),
             alpha = 0.5,
             lineend = c('round'),
              linejoin = c('mitre'),
             show.legend = TRUE) +
    scale_x_continuous(limits = c(-0.6, 0.6)) +
  scale_y_continuous(limits = c(-0.6, 0.6)) +
  geom_abline(alpha = 0.5, linetype = 2) +
  geom_abline(slope = -1, alpha = 0.5, linetype = 2) +
  facet_wrap(~quantile_label) + 
   scale_color_manual(values = c(
  "D1→D3" = "#7400b8",
  "D3→D7" = "#4dbbd5",
  "D1→D7" = "#3c5488"
)) + 
  scale_fill_manual(values = c(
  "D1→D3" = "#7400b8",
  "D3→D7" = "#4dbbd5",
  "D1→D7" = "#3c5488"
)) +
  theme_vaxgo() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.key.width = unit(0.4, 'cm'),
        legend.key.height = unit(0.4, 'cm'),
        legend.title = element_text(size = 10, vjust = 0.9),
        legend.text = element_text(size = 7, vjust = 0.5, hjust = -0.2),
        legend.key = element_rect(colour = NA)) +
  labs(title = "Are these genes well predicted in most timepoints?",
       subtitle = "Differences in mouse to human, using DEGs in human AND mouse, p_adjust < 0.05.\nAll timepoints.",
       x = "Human L2FC",
       y = "Mouse L2FC",
       fill = "Timepoint",
       color = "Timepoint",
       shape = "Timepoint")  

zscore_genes_plot_timepoints
```


```{r}
zscore_genes_plot_timepoints_bar = degs_segments %>% 
  group_by(quantile_label, direction) %>% 
  summarize(n = n()) %>% 
  ungroup() %>% 
  ggplot() +
  aes(x = direction, y = n, fill = direction) +
  geom_col(position = "dodge2", alpha = 0.5) +
  geom_text(aes(label = n),
            position = "dodge2", 
            color = "black",
            hjust = 0.5,
            vjust = -0.5
            ) +
  scale_color_manual(values = c(
  "D1→D3" = "#7400b8",
  "D3→D7" = "#4dbbd5",
  "D1→D7" = "#3c5488"
)) + 
  scale_fill_manual(values = c(
  "D1→D3" = "#7400b8",
  "D3→D7" = "#4dbbd5",
  "D1→D7" = "#3c5488"
)) +
  # scale_x_continuous(expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 110))+
  facet_wrap(~quantile_label) + 
  theme_vaxgo() +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.position = "none") +
  labs(
    # title = "Are these genes well predicted in most timepoints?",
       # subtitle = "Differences in mouse to human, using DEGs in human AND mouse, p_adjust < 0.05.\nAll timepoints. Only Q50 genes.",
       x = "Direction",
       y = "Total",
       fill = "Direction")  

  zscore_genes_plot_timepoints_bar
```

